# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

{ lib, stdenv, nodejs, git, cacert, fetchurl, writeShellScript, writeShellScriptBin }:
{ src, overrideAttrs ? null, ... } @ args:

let

  cacheFolder = ".yarn/cache";

  # Call overrideAttrs on a derivation if a function is provided.
  optionalOverride = fn: drv:
    if fn == null then drv else drv.overrideAttrs fn;

  # Simple stub that provides the global yarn command.
  yarn = writeShellScriptBin "yarn" ''
    exec '${nodejs}/bin/node' '${./.yarn/releases/yarn-3.3.0.cjs}' "$@"
  '';

  # Common attributes between Yarn derivations.
  drvCommon = {
    # Make sure the build uses the right Node.js version everywhere.
    buildInputs = [ nodejs yarn ];
    # Tell node-gyp to use the provided Node.js headers for native code builds.
    npm_config_nodedir = nodejs;
  };

  # Comman variables that we set in a Nix build, but not in a Nix shell.
  buildVars = ''
    # Make Yarn produce friendlier logging for automated builds.
    export CI=1
    # Tell node-pre-gyp to never fetch binaries / always build from source.
    export npm_config_build_from_source=true
    # Disable Nixify plugin to save on some unnecessary processing.
    export yarn_enable_nixify=false
  '';

  # Create derivations for fetching dependencies.
  cacheDrvs =
    let
      builder = writeShellScript "yarn-cache-builder" ''
        source $stdenv/setup
        cd "$src"
        ${buildVars}
        HOME="$TMP" yarn_cache_folder="$TMP" \
          yarn nixify fetch-one $locator
        # Because we change the cache dir, Yarn may generate a different name.
        mv "$TMP/$(sed 's/-[^-]*\.[^-]*$//' <<< "$outputFilename")"-* $out
      '';
    in
    lib.mapAttrs
      (locator: { filename, sha512 }: stdenv.mkDerivation {
        inherit src builder locator;
        name = lib.strings.sanitizeDerivationName locator;
        buildInputs = [ yarn git cacert ];
        outputFilename = filename;
        outputHashMode = "flat";
        outputHashAlgo = "sha512";
        outputHash = sha512;
      })
      cacheEntries;

  # Create a shell snippet to copy dependencies from a list of derivations.
  mkCacheBuilderForDrvs = drvs:
    writeShellScript "collect-yarn-cache" (lib.concatMapStrings
      (drv: ''
        cp ${drv} '${drv.outputFilename}'
      '')
      drvs);


  # Main project derivation.
  project = stdenv.mkDerivation (drvCommon // {
    inherit src;
    name = "nls";

    configurePhase = ''
      ${buildVars}

      # Copy over the Yarn cache.
      rm -fr '${cacheFolder}'
      mkdir -p '${cacheFolder}'
      pushd '${cacheFolder}' > /dev/null
      source ${mkCacheBuilderForDrvs (lib.attrValues cacheDrvs)}
      popd > /dev/null

      # Yarn may need a writable home directory.
      export yarn_global_folder="$TMP"

      # Some node-gyp calls may call out to npm, which could fail due to an
      # read-only home dir.
      export HOME="$TMP"

      # running preConfigure after the cache is populated allows for
      # preConfigure to contain substituteInPlace for dependencies as well as the
      # main project. This is necessary for native bindings that maybe have
      # hardcoded values.
      runHook preConfigure



      # Run normal Yarn install to complete dependency installation.
      yarn install --immutable --immutable-cache

      runHook postConfigure
    '';

    buildPhase = ''
      runHook preBuild
      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall

      mkdir -p "$out/libexec/$name" "$out/bin"

      # Move the package contents to the output directory.
      # - If the package.json has a `files` field, only files matching those patterns are copied
      # - Otherwise all files are copied
      yarn pack --out package.tgz
      tar xzvf package.tgz --directory "$out/libexec/$name" --strip-components=1

      cp .yarnrc* 'yarn.lock' "$out/libexec/$name"
      cp --recursive .yarn "$out/libexec/$name"

      # If the project uses the node-modules linker, then
      # include the node_modules folder in the package.
      if [ -d node_modules ]; then
        cp --recursive node_modules "$out/libexec/$name"
      else
        # Otherwise, assume PnP. Copy the loader into the package.
        cp .pnp.* "$out/libexec/$name"
      fi

      cd "$out/libexec/$name"

      # Invoke a plugin internal command to setup binaries.
      yarn nixify install-bin $out/bin

      # A package with node_modules doesn't need the cache
      if [ -d node_modules ]; then
        yarn cache clean
      fi

      runHook postInstall
    '';

    passthru = {
      inherit nodejs;
      yarn-freestanding = yarn;
      yarn = writeShellScriptBin "yarn" ''
        exec '${yarn}/bin/yarn' --cwd '${project}/libexec/${project.name}' "$@"
      '';
    };
  });

  cacheEntries = {
    "@babel/code-frame@npm:7.12.11" = { filename = "@babel-code-frame-npm-7.12.11-1a9a1b277f-3963eff3eb.zip"; sha512 = "3963eff3ebfb0e091c7e6f99596ef4b258683e4ba8a134e4e95f77afe85be5c931e184fff6435fb4885d12eba04a5e25532f7fbc292ca13b48e7da943474e2f3"; };
    "@babel/helper-validator-identifier@npm:7.19.1" = { filename = "@babel-helper-validator-identifier-npm-7.19.1-d84f19e1dc-0eca5e86a7.zip"; sha512 = "0eca5e86a729162af569b46c6c41a63e18b43dbe09fda1d2a3c8924f7d617116af39cac5e4cd5d431bb760b4dca3c0970e0c444789b1db42bcf1fa41fbad0a3a"; };
    "@babel/highlight@npm:7.18.6" = { filename = "@babel-highlight-npm-7.18.6-9d35ad2e27-92d8ee6154.zip"; sha512 = "92d8ee61549de5ff5120e945e774728e5ccd57fd3b2ed6eace020ec744823d4a98e242be1453d21764a30a14769ecd62170fba28539b211799bbaf232bbb2789"; };
    "@eslint/eslintrc@npm:0.4.3" = { filename = "@eslint-eslintrc-npm-0.4.3-ee1bbcab87-03a7704150.zip"; sha512 = "03a7704150b868c318aab6a94d87a33d30dc2ec579d27374575014f06237ba1370ae11178db772f985ef680d469dc237e7b16a1c5d8edaaeb8c3733e7a95a6d3"; };
    "@gar/promisify@npm:1.1.3" = { filename = "@gar-promisify-npm-1.1.3-ac1a325862-4059f790e2.zip"; sha512 = "4059f790e2d07bf3c3ff3e0fec0daa8144fe35c1f6e0111c9921bd32106adaa97a4ab096ad7dab1e28ee6a9060083c4d1a4ada42a7f5f3f7a96b8812e2b757c1"; };
    "@humanwhocodes/config-array@npm:0.5.0" = { filename = "@humanwhocodes-config-array-npm-0.5.0-5ded120470-44ee6a9f05.zip"; sha512 = "44ee6a9f05d93dd9d5935a006b17572328ba9caff8002442f601736cbda79c580cc0f5a49ce9eb88fbacc5c3a6b62098357c2e95326cd17bb9f1a6c61d6e95e7"; };
    "@humanwhocodes/object-schema@npm:1.2.1" = { filename = "@humanwhocodes-object-schema-npm-1.2.1-eb622b5d0e-a824a1ec31.zip"; sha512 = "a824a1ec31591231e4bad5787641f59e9633827d0a2eaae131a288d33c9ef0290bd16fda8da6f7c0fcb014147865d12118df10db57f27f41e20da92369fcb3f1"; };
    "@nodelib/fs.scandir@npm:2.1.5" = { filename = "@nodelib-fs.scandir-npm-2.1.5-89c67370dd-a970d595bd.zip"; sha512 = "a970d595bd23c66c880e0ef1817791432dbb7acbb8d44b7e7d0e7a22f4521260d4a83f7f9fd61d44fda4610105577f8f58a60718105fb38352baed612fd79e59"; };
    "@nodelib/fs.stat@npm:2.0.5" = { filename = "@nodelib-fs.stat-npm-2.0.5-01f4dd3030-012480b5ca.zip"; sha512 = "012480b5ca9d97bff9261571dbbec7bbc6033f69cc92908bc1ecfad0792361a5a1994bc48674b9ef76419d056a03efadfce5a6cf6dbc0a36559571a7a483f6f0"; };
    "@nodelib/fs.walk@npm:1.2.8" = { filename = "@nodelib-fs.walk-npm-1.2.8-b4a89da548-190c643f15.zip"; sha512 = "190c643f156d8f8f277bf2a6078af1ffde1fd43f498f187c2db24d35b4b4b5785c02c7dc52e356497b9a1b65b13edc996de08de0b961c32844364da02986dc53"; };
    "@npmcli/fs@npm:2.1.2" = { filename = "@npmcli-fs-npm-2.1.2-08d434e77b-405074965e.zip"; sha512 = "405074965e72d4c9d728931b64d2d38e6ea12066d4fad651ac253d175e413c06fe4350970c783db0d749181da8fe49c42d3880bd1cbc12cd68e3a7964d820225"; };
    "@npmcli/move-file@npm:2.0.1" = { filename = "@npmcli-move-file-npm-2.0.1-b593d8f741-52dc02259d.zip"; sha512 = "52dc02259d98da517fae4cb3a0a3850227bdae4939dda1980b788a7670636ca2b4a01b58df03dd5f65c1e3cb70c50fa8ce5762b582b3f499ec30ee5ce1fd9380"; };
    "@tootallnate/once@npm:1.1.2" = { filename = "@tootallnate-once-npm-1.1.2-0517220057-e1fb1bbbc1.zip"; sha512 = "e1fb1bbbc12089a0cb9433dc290f97bddd062deadb6178ce9bcb93bb7c1aecde5e60184bc7065aec42fe1663622a213493c48bbd4972d931aae48315f18e1be9"; };
    "@tootallnate/once@npm:2.0.0" = { filename = "@tootallnate-once-npm-2.0.0-e36cf4f140-ad87447820.zip"; sha512 = "ad87447820dd3f24825d2d947ebc03072b20a42bfc96cbafec16bff8bbda6c1a81fcb0be56d5b21968560c5359a0af4038a68ba150c3e1694fe4c109a063bed8"; };
    "@types/json-schema@npm:7.0.11" = { filename = "@types-json-schema-npm-7.0.11-79462ae5ca-527bddfe62.zip"; sha512 = "527bddfe62db9012fccd7627794bd4c71beb77601861055d87e3ee464f2217c85fca7a4b56ae677478367bbd248dbde13553312b7d4dbc702a2f2bbf60c4018d"; };
    "@types/mocha@npm:8.2.3" = { filename = "@types-mocha-npm-8.2.3-7aff51fdb4-b43ed1b642.zip"; sha512 = "b43ed1b642a2ee62bf10792a07d5d21d66ab8b4d2cf5d822c8a7643e77b90009aecc000eefab5f6ddc9eb69004192f84119a6f97a8499e1a13ea082e7a5e71bf"; };
    "@types/node@npm:12.20.55" = { filename = "@types-node-npm-12.20.55-88487587a4-e4f86785f4.zip"; sha512 = "e4f86785f4092706e0d3b0edff8dca5a13b45627e4b36700acd8dfe6ad53db71928c8dee914d4276c7fd3b6ccd829aa919811c9eb708a2c8e4c6eb3701178c37"; };
    "@types/vscode@npm:1.52.0" = { filename = "@types-vscode-npm-1.52.0-bd83fbd733-e1770f018b.zip"; sha512 = "e1770f018b87123d85e8d04df5bac832e87a5bde172a8d7f18b63f2482624b7fa60baad44b675bfd3035242e5466000321fbdc2158c5236a9363c645b03621d3"; };
    "@typescript-eslint/eslint-plugin@npm:4.33.0" = { filename = "@typescript-eslint-eslint-plugin-npm-4.33.0-b5d1be4879-d74855d0a5.zip"; sha512 = "d74855d0a5ffe0b2f362ec02fcd9301d39a53fb4155b9bd0cb15a0a31d065143129ebf98df9d86af4b6f74de1d423a4c0d8c0095520844068117453afda5bc4f"; };
    "@typescript-eslint/experimental-utils@npm:4.33.0" = { filename = "@typescript-eslint-experimental-utils-npm-4.33.0-f10f287886-f859800ada.zip"; sha512 = "f859800ada0884f92db6856f24efcb1d073ac9883ddc2b1aa9339f392215487895bed8447ebce3741e8141bb32e545244abef62b73193ba9a8a0527c523aabae"; };
    "@typescript-eslint/parser@npm:4.33.0" = { filename = "@typescript-eslint-parser-npm-4.33.0-799c6ce8d5-102457eae1.zip"; sha512 = "102457eae1acd516211098fea081c8a2ed728522bbda7f5a557b6ef23d88970514f9a0f6285d53fca134d3d4d7d17822b5d5e12438d5918df4d1f89cc9e67d57"; };
    "@typescript-eslint/scope-manager@npm:4.33.0" = { filename = "@typescript-eslint-scope-manager-npm-4.33.0-28014c179d-9a25fb7ba7.zip"; sha512 = "9a25fb7ba7c725ea7227a24d315b0f6aacbad002e2549a049edf723c1d3615c22f5c301f0d7d615b377f2cdf2f3519d97e79af0c459de6ef8d2aaf0906dff13e"; };
    "@typescript-eslint/types@npm:4.33.0" = { filename = "@typescript-eslint-types-npm-4.33.0-9e9b956afa-3baae1ca35.zip"; sha512 = "3baae1ca35872421b4eb60f5d3f3f32dc1d513f2ae0a67dee28c7d159fd7a43ed0d11a8a5a0f0c2d38507ffa036fc7c511cb0f18a5e8ac524b3ebde77390ec53"; };
    "@typescript-eslint/typescript-estree@npm:4.33.0" = { filename = "@typescript-eslint-typescript-estree-npm-4.33.0-b6b79c10d0-2566984390.zip"; sha512 = "2566984390c76bd95f43240057215c068c69769e406e27aba41e9f21fd300074d6772e4983fa58fe61e80eb5550af1548d2e31e80550d92ba1d051bb00fe6f5c"; };
    "@typescript-eslint/visitor-keys@npm:4.33.0" = { filename = "@typescript-eslint-visitor-keys-npm-4.33.0-8b7e72a3c9-59953e474a.zip"; sha512 = "59953e474ad4610c1aa23b2b1a964445e2c6201521da6367752f37939d854352bbfced5c04ea539274065e012b1337ba3ffa49c2647a240a4e87155378ba9873"; };
    "@ungap/promise-all-settled@npm:1.1.2" = { filename = "@ungap-promise-all-settled-npm-1.1.2-c0f42e147b-08d37fdfa2.zip"; sha512 = "08d37fdfa23a6fe8139f1305313562ebad973f3fac01bcce2773b2bda5bcb0146dfdcf3cb6a722cf0a5f2ca0bc56a827eac8f1e7b3beddc548f654addf1fc34c"; };
    "@vscode/test-electron@npm:1.6.2" = { filename = "@vscode-test-electron-npm-1.6.2-a82a054189-82a1ce228d.zip"; sha512 = "82a1ce228d028b4073625a7807fbcbcdc10e8fab3d6cee16a8f65255ff7933ce379bf702407530c36971eb706e3ed5659d4af8856245b27a2ae185e75ef0b9fa"; };
    "abbrev@npm:1.1.1" = { filename = "abbrev-npm-1.1.1-3659247eab-a4a97ec07d.zip"; sha512 = "a4a97ec07d7ea112c517036882b2ac22f3109b7b19077dc656316d07d308438aac28e4d9746dc4d84bf6b1e75b4a7b0a5f3cb30592419f128ca9a8cee3bcfa17"; };
    "acorn-jsx@npm:5.3.2" = { filename = "acorn-jsx-npm-5.3.2-d7594599ea-c3d3b2a89c.zip"; sha512 = "c3d3b2a89c9a056b205b69530a37b972b404ee46ec8e5b341666f9513d3163e2a4f214a71f4dfc7370f5a9c07472d2fd1c11c91c3f03d093e37637d95da98950"; };
    "acorn@npm:7.4.1" = { filename = "acorn-npm-7.4.1-f450b4646c-1860f23c21.zip"; sha512 = "1860f23c2107c910c6177b7b7be71be350db9e1080d814493fae143ae37605189504152d1ba8743ba3178d0b37269ce1ffc42b101547fdc1827078f82671e407"; };
    "agent-base@npm:6.0.2" = { filename = "agent-base-npm-6.0.2-428f325a93-f52b6872cc.zip"; sha512 = "f52b6872cc96fd5f622071b71ef200e01c7c4c454ee68bc9accca90c98cfb39f2810e3e9aa330435835eedc8c23f4f8a15267f67c6e245d2b33757575bdac49d"; };
    "agentkeepalive@npm:4.2.1" = { filename = "agentkeepalive-npm-4.2.1-b86a9fb343-39cb49ed8c.zip"; sha512 = "39cb49ed8cf217fd6da058a92828a0a84e0b74c35550f82ee0a10e1ee403c4b78ade7948be2279b188b7a7303f5d396ea2738b134731e464bf28de00a4f72a18"; };
    "aggregate-error@npm:3.1.0" = { filename = "aggregate-error-npm-3.1.0-415a406f4e-1101a33f21.zip"; sha512 = "1101a33f21baa27a2fa8e04b698271e64616b886795fd43c31068c07533c7b3facfcaf4e9e0cab3624bd88f729a592f1c901a1a229c9e490eafce411a8644b79"; };
    "ajv@npm:6.12.6" = { filename = "ajv-npm-6.12.6-4b5105e2b2-874972efe5.zip"; sha512 = "874972efe5c4202ab0a68379481fbd3d1b5d0a7bd6d3cc21d40d3536ebff3352a2a1fabb632d4fd2cc7fe4cbdcd5ed6782084c9bbf7f32a1536d18f9da5007d4"; };
    "ajv@npm:8.11.2" = { filename = "ajv-npm-8.11.2-96b35a945e-53435bf79e.zip"; sha512 = "53435bf79ee7d1eabba8085962dba4c08d08593334b304db7772887f0b7beebc1b3d957432f7437ed4b60e53b5d966a57b439869890209c50fed610459999e3e"; };
    "ansi-colors@npm:4.1.1" = { filename = "ansi-colors-npm-4.1.1-97ad42f223-138d04a510.zip"; sha512 = "138d04a51076cb085da0a7e2d000c5c0bb09f6e772ed5c65c53cb118d37f6c5f1637506d7155fb5f330f0abcf6f12fa2e489ac3f8cdab9da393bf1bb4f9a32b0"; };
    "ansi-colors@npm:4.1.3" = { filename = "ansi-colors-npm-4.1.3-8ffd0ae6c7-a9c2ec8420.zip"; sha512 = "a9c2ec842038a1fabc7db9ece7d3177e2fe1c5dc6f0c51ecfbf5f39911427b89c00b5dc6b8bd95f82a26e9b16aaae2e83d45f060e98070ce4d1333038edceb0e"; };
    "ansi-regex@npm:3.0.1" = { filename = "ansi-regex-npm-3.0.1-01f44078a3-09daf180c5.zip"; sha512 = "09daf180c5f59af9850c7ac1bd7fda85ba596cc8cbeb210826e90755f06c818af86d9fa1e6e8322fab2c3b9e9b03f56c537b42241139f824dd75066a1e7257cc"; };
    "ansi-regex@npm:5.0.1" = { filename = "ansi-regex-npm-5.0.1-c963a48615-2aa4bb54ca.zip"; sha512 = "2aa4bb54caf2d622f1afdad09441695af2a83aa3fe8b8afa581d205e57ed4261c183c4d3877cee25794443fde5876417d859c108078ab788d6af7e4fe52eb66b"; };
    "ansi-styles@npm:3.2.1" = { filename = "ansi-styles-npm-3.2.1-8cb8107983-d85ade01c1.zip"; sha512 = "d85ade01c10e5dd77b6c89f34ed7531da5830d2cb5882c645f330079975b716438cd7ebb81d0d6e6b4f9c577f19ae41ab55f07f19786b02f9dfd9e0377395665"; };
    "ansi-styles@npm:4.3.0" = { filename = "ansi-styles-npm-4.3.0-245c7d42c7-513b44c3b2.zip"; sha512 = "513b44c3b2105dd14cc42a19271e80f386466c4be574bccf60b627432f9198571ebf4ab1e4c3ba17347658f4ee1711c163d574248c0c1cdc2d5917a0ad582ec4"; };
    "anymatch@npm:3.1.3" = { filename = "anymatch-npm-3.1.3-bc81d103b1-3e044fd6d1.zip"; sha512 = "3e044fd6d1d26545f235a9fe4d7a534e2029d8e59fa7fd9f2a6eb21230f6b5380ea1eaf55136e60cbf8e613544b3b766e7a6fa2102e2a3a117505466e3025dc2"; };
    "aproba@npm:2.0.0" = { filename = "aproba-npm-2.0.0-8716bcfde6-5615cadcfb.zip"; sha512 = "5615cadcfb45289eea63f8afd064ab656006361020e1735112e346593856f87435e02d8dcc7ff0d11928bc7d425f27bc7c2a84f6c0b35ab0ff659c814c138a24"; };
    "are-we-there-yet@npm:3.0.1" = { filename = "are-we-there-yet-npm-3.0.1-3395b1512f-52590c2486.zip"; sha512 = "52590c24860fa7173bedeb69a4c05fb573473e860197f618b9a28432ee4379049336727ae3a1f9c4cb083114601c1140cee578376164d0e651217a9843f9fe83"; };
    "argparse@npm:1.0.10" = { filename = "argparse-npm-1.0.10-528934e59d-7ca6e45583.zip"; sha512 = "7ca6e45583a28de7258e39e13d81e925cfa25d7d4aacbf806a382d3c02fcb13403a07fb8aeef949f10a7cfe4a62da0e2e807b348a5980554cc28ee573ef95945"; };
    "argparse@npm:2.0.1" = { filename = "argparse-npm-2.0.1-faff7999e6-83644b5649.zip"; sha512 = "83644b56493e89a254bae05702abf3a1101b4fa4d0ca31df1c9985275a5a5bd47b3c27b7fa0b71098d41114d8ca000e6ed90cad764b306f8a503665e4d517ced"; };
    "array-union@npm:2.1.0" = { filename = "array-union-npm-2.1.0-4e4852b221-5bee12395c.zip"; sha512 = "5bee12395cba82da674931df6d0fea23c4aa4660cb3b338ced9f828782a65caa232573e6bf3968f23e0c5eb301764a382cef2f128b170a9dc59de0e36c39f98d"; };
    "astral-regex@npm:2.0.0" = { filename = "astral-regex-npm-2.0.0-f30d866aab-876231688c.zip"; sha512 = "876231688c66400473ba505731df37ea436e574dd524520294cc3bbc54ea40334865e01fa0d074d74d036ee874ee7e62f486ea38bc421ee8e6a871c06f011766"; };
    "azure-devops-node-api@npm:11.2.0" = { filename = "azure-devops-node-api-npm-11.2.0-4f40e3421f-52e84379b4.zip"; sha512 = "52e84379b4ce71ad8a79470ba89e1d1217b28ee3670c7e484e1b1d9c210acf406ab09132c241cb481f78354df701dae7752ba3c4e3d28b2b6c0b0ff2d9eb7199"; };
    "balanced-match@npm:1.0.2" = { filename = "balanced-match-npm-1.0.2-a53c126459-9706c088a2.zip"; sha512 = "9706c088a283058a8a99e0bf91b0a2f75497f185980d9ffa8b304de1d9e58ebda7c72c07ebf01dadedaac5b2907b2c6f566f660d62bd336c3468e960403b9d65"; };
    "base64-js@npm:1.5.1" = { filename = "base64-js-npm-1.5.1-b2f7275641-669632eb37.zip"; sha512 = "669632eb3745404c2f822a18fc3a0122d2f9a7a13f7fb8b5823ee19d1d2ff9ee5b52c53367176ea4ad093c332fd5ab4bd0ebae5a8e27917a4105a4cfc86b1005"; };
    "big-integer@npm:1.6.51" = { filename = "big-integer-npm-1.6.51-1a244d8e1f-3d444173d1.zip"; sha512 = "3d444173d1b2e20747e2c175568bedeebd8315b0637ea95d75fd27830d3b8e8ba36c6af40374f36bdaea7b5de376dcada1b07587cb2a79a928fccdb6e6e3c518"; };
    "binary-extensions@npm:2.2.0" = { filename = "binary-extensions-npm-2.2.0-180c33fec7-ccd267956c.zip"; sha512 = "ccd267956c58d2315f5d3ea6757cf09863c5fc703e50fbeb13a7dc849b812ef76e3cf9ca8f35a0c48498776a7478d7b4a0418e1e2b8cb9cb9731f2922aaad7f8"; };
    "binary@npm:0.3.0" = { filename = "binary-npm-0.3.0-56515cf10f-b4699fda9e.zip"; sha512 = "b4699fda9e2c2981e74a46b0115cf0d472eda9b68c0e9d229ef494e92f29ce81acf0a834415094cffcc340dfee7c4ef8ce5d048c65c18067a7ed850323f777af"; };
    "bl@npm:4.1.0" = { filename = "bl-npm-4.1.0-7f94cdcf3f-9e8521fa7e.zip"; sha512 = "9e8521fa7e83aa9427c6f8ccdcba6e8167ef30cc9a22df26effcc5ab682ef91d2cbc23a239f945d099289e4bbcfae7a192e9c28c84c6202e710a0dfec3722662"; };
    "bluebird@npm:3.4.7" = { filename = "bluebird-npm-3.4.7-5dff099581-bffa9dee7d.zip"; sha512 = "bffa9dee7d3a41ab15c4f3f24687b49959b4e64e55c058a062176feb8ccefc2163414fb4e1a0f3053bf187600936509660c3ebd168fd9f0e48c7eba23b019466"; };
    "boolbase@npm:1.0.0" = { filename = "boolbase-npm-1.0.0-965fe9af6d-3e25c80ef6.zip"; sha512 = "3e25c80ef626c3a3487c73dbfc70ac322ec830666c9ad915d11b701142fab25ec1e63eff2c450c74347acfd2de854ccde865cd79ef4db1683f7c7b046ea43bb0"; };
    "brace-expansion@npm:1.1.11" = { filename = "brace-expansion-npm-1.1.11-fb95eb05ad-faf34a7bb0.zip"; sha512 = "faf34a7bb0c3fcf4b59c7808bc5d2a96a40988addf2e7e09dfbb67a2251800e0d14cd2bfc1aa79174f2f5095c54ff27f46fb1289fe2d77dac755b5eb3434cc07"; };
    "brace-expansion@npm:2.0.1" = { filename = "brace-expansion-npm-2.0.1-17aa2616f9-a61e7cd2e8.zip"; sha512 = "a61e7cd2e8a8505e9f0036b3b6108ba5e926b4b55089eeb5550cd04a471fe216c96d4fe7e4c7f995c728c554ae20ddfc4244cad10aef255e72b62930afd233d1"; };
    "braces@npm:3.0.2" = { filename = "braces-npm-3.0.2-782240b28a-e2a8e769a8.zip"; sha512 = "e2a8e769a863f3d4ee887b5fe21f63193a891c68b612ddb4b68d82d1b5f3ff9073af066c343e9867a393fe4c2555dcb33e89b937195feb9c1613d259edfcd459"; };
    "browser-stdout@npm:1.3.1" = { filename = "browser-stdout-npm-1.3.1-6b2376bf3f-b717b19b25.zip"; sha512 = "b717b19b25952dd6af483e368f9bcd6b14b87740c3d226c2977a65e84666ffd67000bddea7d911f111a9b6ddc822b234de42d52ab6507bce4119a4cc003ef7b3"; };
    "buffer-crc32@npm:0.2.13" = { filename = "buffer-crc32-npm-0.2.13-c4b6fceac1-06252347ae.zip"; sha512 = "06252347ae6daca3453b94e4b2f1d3754a3b146a111d81c68924c22d91889a40623264e95e67955b1cb4a68cbedf317abeabb5140a9766ed248973096db5ce1c"; };
    "buffer-indexof-polyfill@npm:1.0.2" = { filename = "buffer-indexof-polyfill-npm-1.0.2-39d49d63c8-fbfb2d69c6.zip"; sha512 = "fbfb2d69c6bb2df235683126f9dc140150c08ac3630da149913a9971947b667df816a913b6993bc48f4d611999cb99a1589914d34c02dccd2234afda5cb75bbc"; };
    "buffer@npm:5.7.1" = { filename = "buffer-npm-5.7.1-513ef8259e-e2cf8429e1.zip"; sha512 = "e2cf8429e1c4c7b8cbd30834ac09bd61da46ce35f5c22a78e6c2f04497d6d25541b16881e30a019c6fd3154150650ccee27a308eff3e26229d788bbdeb08ab84"; };
    "buffers@npm:0.1.1" = { filename = "buffers-npm-0.1.1-59dbe6d7fb-ad6f8e483e.zip"; sha512 = "ad6f8e483efab39cefd92bdc04edbff6805e4211b002f4d1cfb70c6c472a61cc89fb18c37bcdfdd4ee416ca096e9ff606286698a7d41a18b539bac12fd76d4d5"; };
    "cacache@npm:16.1.3" = { filename = "cacache-npm-16.1.3-4e2088ed0d-d91409e6e5.zip"; sha512 = "d91409e6e57d7d9a3a25e5dcc589c84e75b178ae8ea7de05cbf6b783f77a5fae938f6e8fda6f5257ed70000be27a681e1e44829251bfffe4c10216002f8f14e6"; };
    "call-bind@npm:1.0.2" = { filename = "call-bind-npm-1.0.2-c957124861-f8e31de9d1.zip"; sha512 = "f8e31de9d19988a4b80f3e704788c4a2d6b6f3d17cfec4f57dc29ced450c53a49270dc66bf0fbd693329ee948dd33e6c90a329519aef17474a4d961e8d6426b0"; };
    "callsites@npm:3.1.0" = { filename = "callsites-npm-3.1.0-268f989910-072d17b6ab.zip"; sha512 = "072d17b6abb459c2ba96598918b55868af677154bec7e73d222ef95a8fdb9bbf7dae96a8421085cdad8cd190d86653b5b6dc55a4484f2e5b2e27d5e0c3fc15b3"; };
    "camelcase@npm:6.3.0" = { filename = "camelcase-npm-6.3.0-e5e42a0d15-8c96818a90.zip"; sha512 = "8c96818a9076434998511251dcb2761a94817ea17dbdc37f47ac080bd088fc62c7369429a19e2178b993497132c8cbcf5cc1f44ba963e76782ba469c0474938d"; };
    "chainsaw@npm:0.1.0" = { filename = "chainsaw-npm-0.1.0-0d34a3db01-22a96b9fb0.zip"; sha512 = "22a96b9fb0cd9fb20813607c0869e61817d1acc81b5d455cc6456b5e460ea1dd52630e0f76b291cf8294bfb6c1fc42e299afb52104af9096242699d6d3aa6d3e"; };
    "chalk@npm:2.4.2" = { filename = "chalk-npm-2.4.2-3ea16dd91e-ec3661d38f.zip"; sha512 = "ec3661d38fe77f681200f878edbd9448821924e0f93a9cefc0e26a33b145f1027a2084bf19967160d11e1f03bfe4eaffcabf5493b89098b2782c3fe0b03d80c2"; };
    "chalk@npm:4.1.2" = { filename = "chalk-npm-4.1.2-ba8b67ab80-fe75c9d5c7.zip"; sha512 = "fe75c9d5c76a7a98d45495b91b2172fa3b7a09e0cc9370e5c8feb1c567b85c4288e2b3fded7cfdd7359ac28d6b3844feb8b82b8686842e93d23c827c417e83fc"; };
    "cheerio-select@npm:2.1.0" = { filename = "cheerio-select-npm-2.1.0-e92bc2f296-843d6d4799.zip"; sha512 = "843d6d479922f28a6c5342c935aff1347491156814de63c585a6eb73baf7bb4185c1b4383a1195dca0f12e3946d737c7763bcef0b9544c515d905c5c44c5308b"; };
    "cheerio@npm:1.0.0-rc.12" = { filename = "cheerio-npm-1.0.0-rc.12-6785a97c2a-5d4c1b7a53.zip"; sha512 = "5d4c1b7a53cf22d3a2eddc0aff70cf23cbb30d01a4c79013e703a012475c02461aa1fcd99127e8d83a02216386ed6942b2c8103845fd0812300dd199e6e7e054"; };
    "chokidar@npm:3.5.1" = { filename = "chokidar-npm-3.5.1-205217279e-b7774e6e3a.zip"; sha512 = "b7774e6e3aeca084d39e8542041555a11452414c744122436101243f89580fad97154ae11525e46bfa816313ae32533e2a88e8587e4d50b14ea716a9e6538978"; };
    "chownr@npm:1.1.4" = { filename = "chownr-npm-1.1.4-5bd400ab08-115648f8eb.zip"; sha512 = "115648f8eb38bac5e41c3857f3e663f9c39ed6480d1349977c4d96c95a47266fcacc5a5aabf3cb6c481e22d72f41992827db47301851766c4fd77ac21a4f081d"; };
    "chownr@npm:2.0.0" = { filename = "chownr-npm-2.0.0-638f1c9c61-c57cf9dd07.zip"; sha512 = "c57cf9dd0791e2f18a5ee9c1a299ae6e801ff58fee96dc8bfd0dcb4738a6ce58dd252a3605b1c93c6418fe4f9d5093b28ffbf4d66648cb2a9c67eaef9679be2f"; };
    "clean-stack@npm:2.2.0" = { filename = "clean-stack-npm-2.2.0-a8ce435a5c-2ac8cd2b2f.zip"; sha512 = "2ac8cd2b2f5ec986a3c743935ec85b07bc174d5421a5efc8017e1f146a1cf5f781ae962618f416352103b32c9cd7e203276e8c28241bbe946160cab16149fb68"; };
    "cliui@npm:7.0.4" = { filename = "cliui-npm-7.0.4-d6b8a9edb6-ce2e8f578a.zip"; sha512 = "ce2e8f578a4813806788ac399b9e866297740eecd4ad1823c27fd344d78b22c5f8597d548adbcc46f0573e43e21e751f39446c5a5e804a12aace402b7a315d7f"; };
    "color-convert@npm:1.9.3" = { filename = "color-convert-npm-1.9.3-1fe690075e-fd7a64a17c.zip"; sha512 = "fd7a64a17cde98fb923b1dd05c5f2e6f7aefda1b60d67e8d449f9328b4e53b228a428fd38bfeaeb2db2ff6b6503a776a996150b80cdf224062af08a5c8a3a203"; };
    "color-convert@npm:2.0.1" = { filename = "color-convert-npm-2.0.1-79730e935b-79e6bdb9fd.zip"; sha512 = "79e6bdb9fd479a205c71d89574fccfb22bd9053bd98c6c4d870d65c132e5e904e6034978e55b43d69fcaa7433af2016ee203ce76eeba9cfa554b373e7f7db336"; };
    "color-name@npm:1.1.3" = { filename = "color-name-npm-1.1.3-728b7b5d39-09c5d3e33d.zip"; sha512 = "09c5d3e33d2105850153b14466501f2bfb30324a2f76568a408763a3b7433b0e50e5b4ab1947868e65cb101bb7cb75029553f2c333b6d4b8138a73fcc133d69d"; };
    "color-name@npm:1.1.4" = { filename = "color-name-npm-1.1.4-025792b0ea-b044585952.zip"; sha512 = "b0445859521eb4021cd0fb0cc1a75cecf67fceecae89b63f62b201cca8d345baf8b952c966862a9d9a2632987d4f6581f0ec8d957dfacece86f0a7919316f610"; };
    "color-support@npm:1.1.3" = { filename = "color-support-npm-1.1.3-3be5c53455-9b73568176.zip"; sha512 = "9b7356817670b9a13a26ca5af1c21615463b500783b739b7634a0c2047c16cef4b2865d7576875c31c3cddf9dd621fa19285e628f20198b233a5cfdda6d0793b"; };
    "commander@npm:6.2.1" = { filename = "commander-npm-6.2.1-d5b635f237-d7090410c0.zip"; sha512 = "d7090410c0de6bc5c67d3ca41c41760d6d268f3c799e530aafb73b7437d1826bbf0d2a3edac33f8b57cc9887b4a986dce307fa5557e109be40eadb7c43b21742"; };
    "concat-map@npm:0.0.1" = { filename = "concat-map-npm-0.0.1-85a921b7ee-902a9f5d89.zip"; sha512 = "902a9f5d8967a3e2faf138d5cb784b9979bad2e6db5357c5b21c568df4ebe62bcb15108af1b2253744844eb964fc023fbd9afbbbb6ddd0bcc204c6fb5b7bf3af"; };
    "console-control-strings@npm:1.1.0" = { filename = "console-control-strings-npm-1.1.0-e3160e5275-8755d76787.zip"; sha512 = "8755d76787f94e6cf79ce4666f0c5519906d7f5b02d4b884cf41e11dcd759ed69c57da0670afd9236d229a46e0f9cf519db0cd829c6dca820bb5a5c3def584ed"; };
    "core-util-is@npm:1.0.3" = { filename = "core-util-is-npm-1.0.3-ca74b76c90-9de8597363.zip"; sha512 = "9de8597363a8e9b9952491ebe18167e3b36e7707569eed0ebf14f8bba773611376466ae34575bca8cfe3c767890c859c74056084738f09d4e4a6f902b2ad7d99"; };
    "cross-spawn@npm:7.0.3" = { filename = "cross-spawn-npm-7.0.3-e4ff3e65b3-671cc7c728.zip"; sha512 = "671cc7c7288c3a8406f3c69a3ae2fc85555c04169e9d611def9a675635472614f1c0ed0ef80955d5b6d4e724f6ced67f0ad1bb006c2ea643488fcfef994d7f52"; };
    "css-select@npm:5.1.0" = { filename = "css-select-npm-5.1.0-9365a79de5-2772c049b1.zip"; sha512 = "2772c049b188d3b8a8159907192e926e11824aea525b8282981f72ba3f349cf9ecd523fdf7734875ee2cb772246c22117fc062da105b6d59afe8dcd5c99c9bda"; };
    "css-what@npm:6.1.0" = { filename = "css-what-npm-6.1.0-57f751efbb-b975e547e1.zip"; sha512 = "b975e547e1e90b79625918f84e67db5d33d896e6de846c9b584094e529f0c63e2ab85ee33b9daffd05bff3a146a1916bec664e18bb76dd5f66cbff9fc13b2bbe"; };
    "debug@npm:4.3.1" = { filename = "debug-npm-4.3.1-22e08d605e-2c3352e37d.zip"; sha512 = "2c3352e37d5c46b0d203317cd45ea0e26b2c99f2d9dfec8b128e6ceba90dfb65425f5331bf3020fe9929d7da8c16758e737f4f3bfc0fce6b8b3d503bae03298b"; };
    "debug@npm:4.3.4" = { filename = "debug-npm-4.3.4-4513954577-3dbad3f94e.zip"; sha512 = "3dbad3f94ea64f34431a9cbf0bafb61853eda57bff2880036153438f50fb5a84f27683ba0d8e5426bf41a8c6ff03879488120cf5b3a761e77953169c0600a708"; };
    "decamelize@npm:4.0.0" = { filename = "decamelize-npm-4.0.0-12410e3409-b7d09b8265.zip"; sha512 = "b7d09b82652c39eead4d6678bb578e3bebd848add894b76d0f6b395bc45b2d692fb88d977e7cfb93c4ed6c119b05a1347cef261174916c2e75c0a8ca57da1809"; };
    "decompress-response@npm:6.0.0" = { filename = "decompress-response-npm-6.0.0-359de2878c-d377cf47e0.zip"; sha512 = "d377cf47e02d805e283866c3f50d3d21578b779731e8c5072d6ce8c13cc31493db1c2f6784da9d1d5250822120cefa44f1deab112d5981015f2e17444b763812"; };
    "deep-extend@npm:0.6.0" = { filename = "deep-extend-npm-0.6.0-e182924219-7be7e5a8d4.zip"; sha512 = "7be7e5a8d468d6b10e6a67c3de828f55001b6eb515d014f7aeb9066ce36bd5717161eb47d6a0f7bed8a9083935b465bc163ee2581c8b128d29bf61092fdf57a7"; };
    "deep-is@npm:0.1.4" = { filename = "deep-is-npm-0.1.4-88938b5a67-edb65dd0d7.zip"; sha512 = "edb65dd0d7d1b9c40b2f50219aef30e116cedd6fc79290e740972c132c09106d2e80aa0bc8826673dd5a00222d4179c84b36a790eef63a4c4bca75a37ef90804"; };
    "delegates@npm:1.0.0" = { filename = "delegates-npm-1.0.0-9b1942d75f-a51744d9b5.zip"; sha512 = "a51744d9b53c164ba9c0492471a1a2ffa0b6727451bdc89e31627fdf4adda9d51277cfcbfb20f0a6f08ccb3c436f341df3e92631a3440226d93a8971724771fd"; };
    "depd@npm:1.1.2" = { filename = "depd-npm-1.1.2-b0c8414da7-6b406620d2.zip"; sha512 = "6b406620d269619852885ce15965272b829df6f409724415e0002c8632ab6a8c0a08ec1f0bd2add05dc7bd7507606f7e2cc034fa24224ab829580040b835ecd9"; };
    "detect-libc@npm:2.0.1" = { filename = "detect-libc-npm-2.0.1-2699cb2ac4-ccb05fcabb.zip"; sha512 = "ccb05fcabbb555beb544d48080179c18523a343face9ee4e1a86605a8715b4169f94d663c21a03c310ac824592f2ba9a5270218819bb411ad7be578a527593d7"; };
    "diff@npm:5.0.0" = { filename = "diff-npm-5.0.0-ad6900db18-f19fe29284.zip"; sha512 = "f19fe29284b633afdb2725c2a8bb7d25761ea54d321d8e67987ac851c5294be4afeab532bd84531e02583a3fe7f4014aa314a3eda84f5590e7a9e6b371ef3b46"; };
    "dir-glob@npm:3.0.1" = { filename = "dir-glob-npm-3.0.1-1aea628b1b-fa05e18324.zip"; sha512 = "fa05e18324510d7283f55862f3161c6759a3f2f8dbce491a2fc14c8324c498286c54282c1f0e933cb930da8419b30679389499b919122952a4f8592362ef4615"; };
    "doctrine@npm:3.0.0" = { filename = "doctrine-npm-3.0.0-c6f1615f04-fd7673ca77.zip"; sha512 = "fd7673ca77fe26cd5cba38d816bc72d641f500f1f9b25b83e8ce28827fe2da7ad583a8da26ab6af85f834138cf8dae9f69b0cd6ab925f52ddab1754db44d99ce"; };
    "dom-serializer@npm:2.0.0" = { filename = "dom-serializer-npm-2.0.0-378ebc7200-cd1810544f.zip"; sha512 = "cd1810544fd8cdfbd51fa2c0c1128ec3a13ba92f14e61b7650b5de421b88205fd2e3f0cc6ace82f13334114addb90ed1c2f23074a51770a8e9c1273acbc7f3e6"; };
    "domelementtype@npm:2.3.0" = { filename = "domelementtype-npm-2.3.0-02de7cbfba-ee837a318f.zip"; sha512 = "ee837a318ff702622f383409d1f5b25dd1024b692ef64d3096ff702e26339f8e345820f29a68bcdcea8cfee3531776b3382651232fbeae95612d6f0a75efb4f6"; };
    "domhandler@npm:5.0.3" = { filename = "domhandler-npm-5.0.3-3ede73dc10-0f58f4a6af.zip"; sha512 = "0f58f4a6af63e6f3a4320aa446d28b5790a009018707bce2859dcb1d21144c7876482b5188395a188dfa974238c019e0a1e610d2fc269a12b2c192ea2b0b131c"; };
    "domutils@npm:3.0.1" = { filename = "domutils-npm-3.0.1-7937818218-23aa7a8405.zip"; sha512 = "23aa7a840572d395220e173cb6263b0d028596e3950100520870a125af33ff819e6f609e1606d6f7d73bd9e7feb03bb404286e57a39063b5384c62b724d987b3"; };
    "duplexer2@npm:0.1.4" = { filename = "duplexer2-npm-0.1.4-6bca6bef12-744961f03c.zip"; sha512 = "744961f03c7f54313f90555ac20284a3fb7bf22fdff6538f041a86c22499560eb6eac9d30ab5768054137cb40e6b18b40f621094e0261d7d8c35a37b7a5ad241"; };
    "emoji-regex@npm:8.0.0" = { filename = "emoji-regex-npm-8.0.0-213764015c-d4c5c39d5a.zip"; sha512 = "d4c5c39d5a9868b5fa152f00cada8a936868fd3367f33f71be515ecee4c803132d11b31a6222b2571b1e5f7e13890156a94880345594d0ce7e3c9895f560f192"; };
    "encoding@npm:0.1.13" = { filename = "encoding-npm-0.1.13-82a1837d30-bb98632f8f.zip"; sha512 = "bb98632f8ffa823996e508ce6a58ffcf5856330fde839ae42c9e1f436cc3b5cc651d4aeae72222916545428e54fd0f6aa8862fd8d25bdbcc4589f1e3f3715e7f"; };
    "end-of-stream@npm:1.4.4" = { filename = "end-of-stream-npm-1.4.4-497fc6dee1-530a5a5a1e.zip"; sha512 = "530a5a5a1e517e962854a31693dbb5c0b2fc40b46dad2a56a2deec656ca040631124f4795823acc68238147805f8b021abbe221f4afed5ef3c8e8efc2024908b"; };
    "enquirer@npm:2.3.6" = { filename = "enquirer-npm-2.3.6-7899175762-1c0911e14a.zip"; sha512 = "1c0911e14a6f8d26721c91e01db06092a5f7675159f0261d69c403396a385afd13dd76825e7678f66daffa930cfaa8d45f506fb35f818a2788463d022af1b884"; };
    "entities@npm:2.1.0" = { filename = "entities-npm-2.1.0-b27b8aebc6-a10a877e48.zip"; sha512 = "a10a877e489586a3f6a691fe49bf3fc4e58f06c8e80522f08214a5150ba457e7017b447d4913a3fa041bda06ee4c92517baa4d8d75373eaa79369e9639225ffd"; };
    "entities@npm:4.4.0" = { filename = "entities-npm-4.4.0-97635dc5cc-84d250329f.zip"; sha512 = "84d250329f4b56b40fa93ed067b194db21e8815e4eb9b59f43a086f0ecd342814f6bc483de8a77da5d64e0f626033192b1b4f1792232a7ea6b970ebe0f3187c2"; };
    "env-paths@npm:2.2.1" = { filename = "env-paths-npm-2.2.1-7c7577428c-65b5df55a8.zip"; sha512 = "65b5df55a8bab92229ab2b40dad3b387fad24613263d103a97f91c9fe43ceb21965cd3392b1ccb5d77088021e525c4e0481adb309625d0cb94ade1d1fb8dc17e"; };
    "err-code@npm:2.0.3" = { filename = "err-code-npm-2.0.3-082e0ff9a7-8b7b1be20d.zip"; sha512 = "8b7b1be20d2de12d2255c0bc2ca638b7af5171142693299416e6a9339bd7d88fc8d7707d913d78e0993176005405a236b066b45666b27b797252c771156ace54"; };
    "escalade@npm:3.1.1" = { filename = "escalade-npm-3.1.1-e02da076aa-a3e2a99f07.zip"; sha512 = "a3e2a99f07acb74b3ad4989c48ca0c3140f69f923e56d0cba0526240ee470b91010f9d39001f2a4a313841d237ede70a729e92125191ba5d21e74b106800b133"; };
    "escape-string-regexp@npm:1.0.5" = { filename = "escape-string-regexp-npm-1.0.5-3284de402f-6092fda75c.zip"; sha512 = "6092fda75c63b110c706b6a9bfde8a612ad595b628f0bd2147eea1d3406723020810e591effc7db1da91d80a71a737a313567c5abb3813e8d9c71f4aa595b410"; };
    "escape-string-regexp@npm:4.0.0" = { filename = "escape-string-regexp-npm-4.0.0-4b531d8d59-98b48897d9.zip"; sha512 = "98b48897d93060f2322108bf29db0feba7dd774be96cd069458d1453347b25ce8682ecc39859d4bca2203cc0ab19c237bcc71755eff49a0f8d90beadeeba5cc5"; };
    "eslint-scope@npm:5.1.1" = { filename = "eslint-scope-npm-5.1.1-71fe59b18a-47e4b6a3f0.zip"; sha512 = "47e4b6a3f0cc29c7feedee6c67b225a2da7e155802c6ea13bbef4ac6b9e10c66cd2dcb987867ef176292bf4e64eccc680a49e35e9e9c669f4a02bac17e86abdb"; };
    "eslint-utils@npm:2.1.0" = { filename = "eslint-utils-npm-2.1.0-a3a7ebf4fa-27500938f3.zip"; sha512 = "27500938f348da42100d9e6ad03ae29b3de19ba757ae1a7f4a087bdcf83ac60949bbb54286492ca61fac1f5f3ac8692dd21537ce6214240bf95ad0122f24d71d"; };
    "eslint-utils@npm:3.0.0" = { filename = "eslint-utils-npm-3.0.0-630b3a4013-0668fe02f5.zip"; sha512 = "0668fe02f5adab2e5a367eee5089f4c39033af20499df88fe4e6aba2015c20720404d8c3d6349b6f716b08fdf91b9da4e5d5481f265049278099c4c836ccb619"; };
    "eslint-visitor-keys@npm:1.3.0" = { filename = "eslint-visitor-keys-npm-1.3.0-c07780a0fb-37a19b712f.zip"; sha512 = "37a19b712f42f4c9027e8ba98c2b06031c17e0c0a4c696cd429bd9ee04eb43889c446f2cd545e1ff51bef9593fcec94ecd2c2ef89129fcbbf3adadbef520376a"; };
    "eslint-visitor-keys@npm:2.1.0" = { filename = "eslint-visitor-keys-npm-2.1.0-c31806b6b9-e3081d7dd2.zip"; sha512 = "e3081d7dd2611a35f0388bbdc2f5da60b3a3c5b8b6e928daffff7391146b434d691577aa95064c8b7faad0b8a680266bcda0a42439c18c717b80e6718d7e267d"; };
    "eslint@npm:7.32.0" = { filename = "eslint-npm-7.32.0-e15cc6682f-cc85af9985.zip"; sha512 = "cc85af9985a3a11085c011f3d27abe8111006d34cc274291b3c4d7bea51a4e2ff6135780249becd919ba7f6d6d1ecc38a6b73dacb6a7be08d38453b344dc8d37"; };
    "espree@npm:7.3.1" = { filename = "espree-npm-7.3.1-8d8ea5d1e3-aa9b50dcce.zip"; sha512 = "aa9b50dcce883449af2e23bc2b8d9abb77118f96f4cb313935d6b220f77137eaef7724a83c3f6243b96bc0e4ab14766198e60818caad99f9519ae5a336a39b45"; };
    "esprima@npm:4.0.1" = { filename = "esprima-npm-4.0.1-1084e98778-b45bc805a6.zip"; sha512 = "b45bc805a613dbea2835278c306b91aff6173c8d034223fa81498c77dcbce3b2931bf6006db816f62eacd9fd4ea975dfd85a5b7f3c6402cfd050d4ca3c13a628"; };
    "esquery@npm:1.4.0" = { filename = "esquery-npm-1.4.0-f39408b1a7-a0807e17ab.zip"; sha512 = "a0807e17abd7fbe5fbd4fab673038d6d8a50675cdae6b04fbaa520c34581be0c5fa24582990e8acd8854f671dd291c78bb2efb9e0ed5b62f33bac4f9cf820210"; };
    "esrecurse@npm:4.3.0" = { filename = "esrecurse-npm-4.3.0-10b86a887a-ebc17b1a33.zip"; sha512 = "ebc17b1a33c51cef46fdc28b958994b1dc43cd2e86237515cbc3b4e5d2be6a811b2315d0a1a4d9d340b6d2308b15322f5c8291059521cc5f4802f65e7ec32837"; };
    "estraverse@npm:4.3.0" = { filename = "estraverse-npm-4.3.0-920a32f3c6-a6299491f9.zip"; sha512 = "a6299491f9940bb246124a8d44b7b7a413a8336f5436f9837aaa9330209bd9ee8af7e91a654a3545aee9c54b3308e78ee360cef1d777d37cfef77d2fa33b5827"; };
    "estraverse@npm:5.3.0" = { filename = "estraverse-npm-5.3.0-03284f8f63-072780882d.zip"; sha512 = "072780882dc8416ad144f8fe199628d2b3e7bbc9989d9ed43795d2c90309a2047e6bc5979d7e2322a341163d22cfad9e21f4110597fe487519697389497e4e2b"; };
    "esutils@npm:2.0.3" = { filename = "esutils-npm-2.0.3-f865beafd5-22b5b08f74.zip"; sha512 = "22b5b08f74737379a840b8ed2036a5fb35826c709ab000683b092d9054e5c2a82c27818f12604bfc2a9a76b90b6834ef081edbc1c7ae30d1627012e067c6ec87"; };
    "expand-template@npm:2.0.3" = { filename = "expand-template-npm-2.0.3-80de959306-588c198472.zip"; sha512 = "588c19847216421ed92befb521767b7018dc88f88b0576df98cb242f20961425e96a92cbece525ef28cc5becceae5d544ae0f5b9b5e2aa05acb13716ca5b3099"; };
    "fast-deep-equal@npm:3.1.3" = { filename = "fast-deep-equal-npm-3.1.3-790edcfcf5-e21a9d8d84.zip"; sha512 = "e21a9d8d84f53493b6aa15efc9cfd53dd5b714a1f23f67fb5dc8f574af80df889b3bce25dc081887c6d25457cce704e636395333abad896ccdec03abaf1f3f9d"; };
    "fast-glob@npm:3.2.12" = { filename = "fast-glob-npm-3.2.12-162763bbae-0b1990f6ce.zip"; sha512 = "0b1990f6ce831c7e28c4d505edcdaad8e27e88ab9fa65eedadb730438cfc7cde4910d6c975d6b7b8dc8a73da4773702ebcfcd6e3518e73938bb1383badfe01c2"; };
    "fast-json-stable-stringify@npm:2.1.0" = { filename = "fast-json-stable-stringify-npm-2.1.0-02e8905fda-b191531e36.zip"; sha512 = "b191531e36c607977e5b1c47811158733c34ccb3bfde92c44798929e9b4154884378536d26ad90dfecd32e1ffc09c545d23535ad91b3161a27ddbb8ebe0cbecb"; };
    "fast-levenshtein@npm:2.0.6" = { filename = "fast-levenshtein-npm-2.0.6-fcd74b8df5-92cfec0a8d.zip"; sha512 = "92cfec0a8dfafd9c7a15fba8f2cc29cd0b62b85f056d99ce448bbcd9f708e18ab2764bda4dd5158364f4145a7c72788538994f0d1787b956ef0d1062b0f7c24c"; };
    "fastq@npm:1.13.0" = { filename = "fastq-npm-1.13.0-a45963881c-32cf15c29a.zip"; sha512 = "32cf15c29afe622af187d12fc9cd93e160a0cb7c31a3bb6ace86b7dea3b28e7b72acde89c882663f307b2184e14782c6c664fa315973c03626c7d4bff070bb0b"; };
    "fd-slicer@npm:1.1.0" = { filename = "fd-slicer-npm-1.1.0-3cade0050a-c8585fd571.zip"; sha512 = "c8585fd5713f4476eb8261150900d2cb7f6ff2d87f8feb306ccc8a1122efd152f1783bdb2b8dc891395744583436bfd8081d8e63ece0ec8687eeefea394d4ff2"; };
    "file-entry-cache@npm:6.0.1" = { filename = "file-entry-cache-npm-6.0.1-31965cf0af-f49701feaa.zip"; sha512 = "f49701feaa6314c8127c3c2f6173cfefff17612f5ed2daaafc6da13b5c91fd43e3b2a58fd0d63f9f94478a501b167615931e7200e31485e320f74a33885a9c74"; };
    "fill-range@npm:7.0.1" = { filename = "fill-range-npm-7.0.1-b8b1817caa-cc283f4e65.zip"; sha512 = "cc283f4e65b504259e64fd969bcf4def4eb08d85565e906b7d36516e87819db52029a76b6363d0f02d0d532f0033c9603b9e2d943d56ee3b0d4f7ad3328ff917"; };
    "find-up@npm:5.0.0" = { filename = "find-up-npm-5.0.0-e03e9b796d-07955e3573.zip"; sha512 = "07955e357348f34660bde7920783204ff5a26ac2cafcaa28bace494027158a97b9f56faaf2d89a6106211a8174db650dd9f503f9c0d526b1202d5554a00b9095"; };
    "flat-cache@npm:3.0.4" = { filename = "flat-cache-npm-3.0.4-ee77e5911e-4fdd10ecbc.zip"; sha512 = "4fdd10ecbcbf7d520f9040dd1340eb5dfe951e6f0ecf2252edeec03ee68d989ec8b9a20f4434270e71bcfd57800dc09b3344fca3966b2eb8f613072c7d9a2365"; };
    "flat@npm:5.0.2" = { filename = "flat-npm-5.0.2-12748102a5-12a1536ac7.zip"; sha512 = "12a1536ac746db74881316a181499a78ef953632ddd28050b7a3a43c62ef5462e3357c8c29d76072bb635f147f7a9a1f0c02efef6b4be28f8db62ceb3d5c7f5d"; };
    "flatted@npm:3.2.7" = { filename = "flatted-npm-3.2.7-0da10b7c56-427633049d.zip"; sha512 = "427633049d55bdb80201c68f7eb1cbd533e03eac541f97d3aecab8c5526f12a20ccecaeede08b57503e772c769e7f8680b37e8d482d1e5f8d7e2194687f9ea35"; };
    "fs-constants@npm:1.0.0" = { filename = "fs-constants-npm-1.0.0-59576b2177-18f5b71837.zip"; sha512 = "18f5b718371816155849475ac36c7d0b24d39a11d91348cfcb308b4494824413e03572c403c86d3a260e049465518c4f0d5bd00f0371cdfcad6d4f30a85b350d"; };
    "fs-minipass@npm:2.1.0" = { filename = "fs-minipass-npm-2.1.0-501ef87306-1b8d128dae.zip"; sha512 = "1b8d128dae2ac6cc94230cc5ead341ba3e0efaef82dab46a33d171c044caaa6ca001364178d42069b2809c35a1c3c35079a32107c770e9ffab3901b59af8c8b1"; };
    "fs.realpath@npm:1.0.0" = { filename = "fs.realpath-npm-1.0.0-c8f05d8126-99ddea01a7.zip"; sha512 = "99ddea01a7e75aa276c250a04eedeffe5662bce66c65c07164ad6264f9de18fb21be9433ead460e54cff20e31721c811f4fb5d70591799df5f85dce6d6746fd0"; };
    "fsevents@npm:2.3.2" = { filename = "fsevents-npm-2.3.2-a881d6ac9f-97ade64e75.zip"; sha512 = "97ade64e75091afee5265e6956cb72ba34db7819b4c3e94c431d4be2b19b8bb7a2d4116da417950c3425f17c8fe693d25e20212cac583ac1521ad066b77ae31f"; };
    "fstream@npm:1.0.12" = { filename = "fstream-npm-1.0.12-db27e8a713-e6998651ae.zip"; sha512 = "e6998651aeb85fd0f0a8a68cec4d05a3ada685ecc4e3f56e0d063d0564a4fc39ad11a856f9020f926daf869fc67f7a90e891def5d48e4cadab875dc313094536"; };
    "function-bind@npm:1.1.1" = { filename = "function-bind-npm-1.1.1-b56b322ae9-b32fbaebb3.zip"; sha512 = "b32fbaebb3f8ec4969f033073b43f5c8befbb58f1a79e12f1d7490358150359ebd92f49e72ff0144f65f2c48ea2a605bff2d07965f548f6474fd8efd95bf361a"; };
    "functional-red-black-tree@npm:1.0.1" = { filename = "functional-red-black-tree-npm-1.0.1-ccfe924dcd-ca6c170f37.zip"; sha512 = "ca6c170f37640e2d94297da8bb4bf27a1d12bea3e00e6a3e007fd7aa32e37e000f5772acf941b4e4f3cf1c95c3752033d0c509af157ad8f526e7f00723b9eb9f"; };
    "gauge@npm:4.0.4" = { filename = "gauge-npm-4.0.4-8f878385e9-788b6bfe52.zip"; sha512 = "788b6bfe52f1dd8e263cda800c26ac0ca2ff6de0b6eee2fe0d9e3abf15e149b651bd27bf5226be10e6e3edb5c4e5d5985a5a1a98137e7a892f75eff76467ad2d"; };
    "get-caller-file@npm:2.0.5" = { filename = "get-caller-file-npm-2.0.5-80e8a86305-b9769a836d.zip"; sha512 = "b9769a836d2a98c3ee734a88ba712e62703f1df31b94b784762c433c27a386dd6029ff55c2a920c392e33657d80191edbf18c61487e198844844516f843496b9"; };
    "get-intrinsic@npm:1.1.3" = { filename = "get-intrinsic-npm-1.1.3-b6c7bd1010-152d79e872.zip"; sha512 = "152d79e87251d536cf880ba75cfc3d6c6c50e12b3a64e1ea960e73a3752b47c69f46034456eae1b0894359ce3bc64c55c186f2811f8a788b75b638b06fab228a"; };
    "github-from-package@npm:0.0.0" = { filename = "github-from-package-npm-0.0.0-519f80c9a1-14e448192a.zip"; sha512 = "14e448192a35c1e42efee94c9d01a10f42fe790375891a24b25261246ce9336ab9df5d274585aedd4568f7922246c2a78b8a8cd2571bfe99c693a9718e7dd0e3"; };
    "glob-parent@npm:5.1.2" = { filename = "glob-parent-npm-5.1.2-021ab32634-f4f2bfe242.zip"; sha512 = "f4f2bfe2425296e8a47e36864e4f42be38a996db40420fe434565e4480e3322f18eb37589617a98640c5dc8fdec1a387007ee18dbb1f3f5553409c34d17f425e"; };
    "glob@npm:7.1.6" = { filename = "glob-npm-7.1.6-1ce3a5189a-351d549dd9.zip"; sha512 = "351d549dd90553b87c2d3f90ce11aed9e1093c74130440e7ae0592e11bbcd2ce7f0ebb8ba6bfe63aaf9b62166a7f4c80cb84490ae5d78408bb2572bf7d4ee0a6"; };
    "glob@npm:7.2.3" = { filename = "glob-npm-7.2.3-2d866d17a5-29452e97b3.zip"; sha512 = "29452e97b38fa704dabb1d1045350fb2467cf0277e155aa9ff7077e90ad81d1ea9d53d3ee63bd37c05b09a065e90f16aec4a65f5b8de401d1dac40bc5605d133"; };
    "glob@npm:8.0.3" = { filename = "glob-npm-8.0.3-750f909025-50bcdea19d.zip"; sha512 = "50bcdea19d8e79d8de5f460b1939ffc2b3299eac28deb502093fdca22a78efebc03e66bf54f0abc3d3d07d8134d19a32850288b7440d77e072aa55f9d33b18c5"; };
    "globals@npm:13.18.0" = { filename = "globals-npm-13.18.0-0272e9ed61-9fdaa74cfd.zip"; sha512 = "9fdaa74cfd5d4ac91319662f512c29b11d1d2deb9c8a20d3998097671deba83d195f20730b2345887de3ddab958a6fa68952feed9ae836ee4594a82ace62fdb4"; };
    "globby@npm:11.1.0" = { filename = "globby-npm-11.1.0-bdcdf20c71-b4be8885e0.zip"; sha512 = "b4be8885e0cfa018fc783792942d53926c35c50b3aefd3fdcfb9d22c627639dc26bd2327a40a0b74b074100ce95bb7187bfeae2f236856aa3de183af7a02aea6"; };
    "graceful-fs@npm:4.2.10" = { filename = "graceful-fs-npm-4.2.10-79c70989ca-3f109d70ae.zip"; sha512 = "3f109d70ae123951905d85032ebeae3c2a5a7a997430df00ea30df0e3a6c60cf6689b109654d6fdacd28810a053348c4d14642da1d075049e6be1ba5216218da"; };
    "growl@npm:1.10.5" = { filename = "growl-npm-1.10.5-2d1da54198-4b86685de6.zip"; sha512 = "4b86685de6831cebcbb19f93870bea624afee61124b0a20c49017013987cd129e73a8c4baeca295728f41d21265e1f859d25ef36731b142ca59c655fea94bb1a"; };
    "has-flag@npm:3.0.0" = { filename = "has-flag-npm-3.0.0-16ac11fe05-4a15638b45.zip"; sha512 = "4a15638b454bf086c8148979aae044dd6e39d63904cd452d970374fa6a87623423da485dfb814e7be882e05c096a7ccf1ebd48e7e7501d0208d8384ff4dea73b"; };
    "has-flag@npm:4.0.0" = { filename = "has-flag-npm-4.0.0-32af9f0536-261a135703.zip"; sha512 = "261a1357037ead75e338156b1f9452c016a37dcd3283a972a30d9e4a87441ba372c8b81f818cd0fbcd9c0354b4ae7e18b9e1afa1971164aef6d18c2b6095a8ad"; };
    "has-symbols@npm:1.0.3" = { filename = "has-symbols-npm-1.0.3-1986bff2c4-a054c40c63.zip"; sha512 = "a054c40c631c0d5741a8285010a0777ea0c068f99ed43e5d6eb12972da223f8af553a455132fdb0801bdcfa0e0f443c0c03a68d8555aa529b3144b446c3f2410"; };
    "has-unicode@npm:2.0.1" = { filename = "has-unicode-npm-2.0.1-893adb4747-1eab07a743.zip"; sha512 = "1eab07a7436512db0be40a710b29b5dc21fa04880b7f63c9980b706683127e3c1b57cb80ea96d47991bdae2dfe479604f6a1ba410106ee1046a41d1bd0814400"; };
    "has@npm:1.0.3" = { filename = "has-npm-1.0.3-b7f00631c1-b9ad53d53b.zip"; sha512 = "b9ad53d53be4af90ce5d1c38331e712522417d017d5ef1ebd0507e07c2fbad8686fffb8e12ddecd4c39ca9b9b47431afbb975b8abf7f3c3b82c98e9aad052792"; };
    "he@npm:1.2.0" = { filename = "he-npm-1.2.0-3b73a2ff07-3d4d6babcc.zip"; sha512 = "3d4d6babccccd79c5c5a3f929a68af33360d6445587d628087f39a965079d84f18ce9c3d3f917ee1e3978916fc833bb8b29377c3b403f919426f91bc6965e7a7"; };
    "hosted-git-info@npm:4.1.0" = { filename = "hosted-git-info-npm-4.1.0-4efcdf8fd3-c3f87b3c2f.zip"; sha512 = "c3f87b3c2f7eb8c2748c8f49c0c2517c9a95f35d26f4bf54b2a8cba05d2e668f3753548b6ea366b18ec8dadb4e12066e19fa382a01496b0ffa0497eb23cbe461"; };
    "htmlparser2@npm:8.0.1" = { filename = "htmlparser2-npm-8.0.1-b432299617-06d5c71e83.zip"; sha512 = "06d5c71e8313597722bc429ae2a7a8333d77bd3ab07ccb916628384b37332027b047f8619448d8f4a3312b6609c6ea3302a4e77435d859e9e686999e6699ca39"; };
    "http-cache-semantics@npm:4.1.0" = { filename = "http-cache-semantics-npm-4.1.0-860520a31f-974de94a81.zip"; sha512 = "974de94a81c5474be07f269f9fd8383e92ebb5a448208223bfb39e172a9dbc26feff250192ecc23b9593b3f92098e010406b0f24bd4d588d631f80214648ed42"; };
    "http-proxy-agent@npm:4.0.1" = { filename = "http-proxy-agent-npm-4.0.1-ce9ef61788-c6a5da5a19.zip"; sha512 = "c6a5da5a1929416b6bbdf77b1aca13888013fe7eb9d59fc292e25d18e041bb154a8dfada58e223fc7b76b9b2d155a87e92e608235201f77d34aa258707963a82"; };
    "http-proxy-agent@npm:5.0.0" = { filename = "http-proxy-agent-npm-5.0.0-7f1f121b83-e2ee1ff165.zip"; sha512 = "e2ee1ff1656a131953839b2a19cd1f3a52d97c25ba87bd2559af6ae87114abf60971e498021f9b73f9fd78aea8876d1fb0d4656aac8a03c6caa9fc175f22b786"; };
    "https-proxy-agent@npm:5.0.1" = { filename = "https-proxy-agent-npm-5.0.1-42d65f358e-571fccdf38.zip"; sha512 = "571fccdf38184f05943e12d37d6ce38197becdd69e58d03f43637f7fa1269cf303a7d228aa27e5b27bbd3af8f09fd938e1c91dcfefff2df7ba77c20ed8dfc765"; };
    "humanize-ms@npm:1.2.1" = { filename = "humanize-ms-npm-1.2.1-e942bd7329-9c7a74a282.zip"; sha512 = "9c7a74a2827f9294c009266c82031030eae811ca87b0da3dceb8d6071b9bde22c9f3daef0469c3c533cc67a97d8a167cd9fc0389350e5f415f61a79b171ded16"; };
    "iconv-lite@npm:0.6.3" = { filename = "iconv-lite-npm-0.6.3-24b8aae27e-3f60d47a5c.zip"; sha512 = "3f60d47a5c8fc3313317edfd29a00a692cc87a19cac0159e2ce711d0ebc9019064108323b5e493625e25594f11c6236647d8e256fbe7a58f4a3b33b89e6d30bf"; };
    "ieee754@npm:1.2.1" = { filename = "ieee754-npm-1.2.1-fb63b3caeb-5144c0c981.zip"; sha512 = "5144c0c9815e54ada181d80a0b810221a253562422e7c6c3a60b1901154184f49326ec239d618c416c1c5945a2e197107aee8d986a3dd836b53dffefd99b5e7e"; };
    "ignore@npm:4.0.6" = { filename = "ignore-npm-4.0.6-66c0d6543e-248f82e50a.zip"; sha512 = "248f82e50a430906f9ee7f35e1158e3ec4c3971451dd9f99c9bc1548261b4db2b99709f60ac6c6cac9333494384176cc4cc9b07acbe42d52ac6a09cad734d800"; };
    "ignore@npm:5.2.0" = { filename = "ignore-npm-5.2.0-fc4b58a4f3-6b1f926792.zip"; sha512 = "6b1f926792d614f64c6c83da3a1f9c83f6196c2839aa41e1e32dd7b8d174cef2e329d75caabb62cb61ce9dc432f75e67d07d122a037312db7caa73166a1bdb77"; };
    "import-fresh@npm:3.3.0" = { filename = "import-fresh-npm-3.3.0-3e34265ca9-2cacfad06e.zip"; sha512 = "2cacfad06e652b1edc50be650f7ec3be08c5e5a6f6d12d035c440a42a8cc028e60a5b99ca08a77ab4d6b1346da7d971915828f33cdab730d3d42f08242d09baa"; };
    "imurmurhash@npm:0.1.4" = { filename = "imurmurhash-npm-0.1.4-610c5068a0-7cae75c8cd.zip"; sha512 = "7cae75c8cd9a50f57dadd77482359f659eaebac0319dd9368bcd1714f55e65badd6929ca58569da2b6494ef13fdd5598cd700b1eba23f8b79c5f19d195a3ecf7"; };
    "indent-string@npm:4.0.0" = { filename = "indent-string-npm-4.0.0-7b717435b2-824cfb9929.zip"; sha512 = "824cfb9929d031dabf059bebfe08cf3137365e112019086ed3dcff6a0a7b698cb80cf67ccccde0e25b9e2d7527aa6cc1fed1ac490c752162496caba3e6699612"; };
    "infer-owner@npm:1.0.4" = { filename = "infer-owner-npm-1.0.4-685ac3d2af-181e732764.zip"; sha512 = "181e732764e4a0611576466b4b87dac338972b839920b2a8cde43642e4ed6bd54dc1fb0b40874728f2a2df9a1b097b8ff83b56d5f8f8e3927f837fdcb47d8a89"; };
    "inflight@npm:1.0.6" = { filename = "inflight-npm-1.0.6-ccedb4b908-f4f76aa072.zip"; sha512 = "f4f76aa072ce19fae87ce1ef7d221e709afb59d445e05d47fba710e85470923a75de35bfae47da6de1b18afc3ce83d70facf44cfb0aff89f0a3f45c0a0244dfd"; };
    "inherits@npm:2.0.4" = { filename = "inherits-npm-2.0.4-c66b3957a0-4a48a73384.zip"; sha512 = "4a48a733847879d6cf6691860a6b1e3f0f4754176e4d71494c41f3475553768b10f84b5ce1d40fbd0e34e6bfbb864ee35858ad4dd2cf31e02fc4a154b724d7f1"; };
    "ini@npm:1.3.8" = { filename = "ini-npm-1.3.8-fb5040b4c0-dfd98b0ca3.zip"; sha512 = "dfd98b0ca3a4fc1e323e38a6c8eb8936e31a97a918d3b377649ea15bdb15d481207a0dda1021efbd86b464cae29a0d33c1d7dcaf6c5672bee17fa849bc50a1b3"; };
    "ip@npm:2.0.0" = { filename = "ip-npm-2.0.0-204facb3cc-cfcfac6b87.zip"; sha512 = "cfcfac6b873b701996d71ec82a7dd27ba92450afdb421e356f44044ed688df04567344c36cbacea7d01b1c39a4c732dc012570ebe9bebfb06f27314bca625349"; };
    "is-binary-path@npm:2.1.0" = { filename = "is-binary-path-npm-2.1.0-e61d46f557-84192eb88c.zip"; sha512 = "84192eb88cff70d320426f35ecd63c3d6d495da9d805b19bc65b518984b7c0760280e57dbf119b7e9be6b161784a5a673ab2c6abe83abb5198a432232ad5b35c"; };
    "is-extglob@npm:2.1.1" = { filename = "is-extglob-npm-2.1.1-0870ea68b5-df033653d0.zip"; sha512 = "df033653d06d0eb567461e58a7a8c9f940bd8c22274b94bf7671ab36df5719791aae15eef6d83bbb5e23283967f2f984b8914559d4449efda578c775c4be6f85"; };
    "is-fullwidth-code-point@npm:2.0.0" = { filename = "is-fullwidth-code-point-npm-2.0.0-507f56ec71-eef9c6e15f.zip"; sha512 = "eef9c6e15f68085fec19ff6a978a6f1b8f48018fd1265035552078ee945573594933b09bbd6f562553e2a241561439f1ef5339276eba68d272001343084cfab8"; };
    "is-fullwidth-code-point@npm:3.0.0" = { filename = "is-fullwidth-code-point-npm-3.0.0-1ecf4ebee5-44a30c2945.zip"; sha512 = "44a30c29457c7fb8f00297bce733f0a64cd22eca270f83e58c105e0d015e45c019491a4ab2faef91ab51d4738c670daff901c799f6a700e27f7314029e99e348"; };
    "is-glob@npm:4.0.3" = { filename = "is-glob-npm-4.0.3-cb87bf1bdb-d381c1319f.zip"; sha512 = "d381c1319fcb69d341cc6e6c7cd588e17cd94722d9a32dbd60660b993c4fb7d0f19438674e68dfec686d09b7c73139c9166b47597f846af387450224a8101ab4"; };
    "is-lambda@npm:1.0.1" = { filename = "is-lambda-npm-1.0.1-7ab55bc8a8-93a32f0194.zip"; sha512 = "93a32f01940220532e5948538699ad610d5924ac86093fcee83022252b363eb0cc99ba53ab084a04e4fb62bf7b5731f55496257a4c38adf87af9c4d352c71c35"; };
    "is-number@npm:7.0.0" = { filename = "is-number-npm-7.0.0-060086935c-456ac6f8e0.zip"; sha512 = "456ac6f8e0f3111ed34668a624e45315201dff921e5ac181f8ec24923b99e9f32ca1a194912dc79d539c97d33dba17dc635202ff0b2cf98326f608323276d27a"; };
    "is-plain-obj@npm:2.1.0" = { filename = "is-plain-obj-npm-2.1.0-8dffd7ae9c-cec9100678.zip"; sha512 = "cec9100678b0a9fe0248a81743041ed990c2d4c99f893d935545cfbc42876cbe86d207f3b895700c690ad2fa520e568c44afc1605044b535a7820c1d40e38daa"; };
    "isarray@npm:1.0.0" = { filename = "isarray-npm-1.0.0-db4f547720-f032df8e02.zip"; sha512 = "f032df8e02dce8ec565cf2eb605ea939bdccea528dbcf565cdf92bfa2da9110461159d86a537388ef1acef8815a330642d7885b29010e8f7eac967c9993b65ab"; };
    "isexe@npm:2.0.0" = { filename = "isexe-npm-2.0.0-b58870bd2e-26bf6c5480.zip"; sha512 = "26bf6c5480dda5161c820c5b5c751ae1e766c587b1f951ea3fcfc973bafb7831ae5b54a31a69bd670220e42e99ec154475025a468eae58ea262f813fdc8d1c62"; };
    "js-tokens@npm:4.0.0" = { filename = "js-tokens-npm-4.0.0-0ac852e9e2-8a95213a5a.zip"; sha512 = "8a95213a5a77deb6cbe94d86340e8d9ace2b93bc367790b260101d2f36a2eaf4e4e22d9fa9cf459b38af3a32fb4190e638024cf82ec95ef708680e405ea7cc78"; };
    "js-yaml@npm:3.14.1" = { filename = "js-yaml-npm-3.14.1-b968c6095e-bef146085f.zip"; sha512 = "bef146085f472d44dee30ec34e5cf36bf89164f5d585435a3d3da89e52622dff0b188a580e4ad091c3341889e14cb88cac6e4deb16dc5b1e9623bb0601fc255c"; };
    "js-yaml@npm:4.0.0" = { filename = "js-yaml-npm-4.0.0-3ac8e950bb-931d6dddb3.zip"; sha512 = "931d6dddb3589fa272c8273366c6dffa99fd6bd26ac7b70f9bac925c28cb7ae352b964192df84f90ecd7a2ff50ab87e6d58e2148eb19c89aa155c73ed847ab92"; };
    "json-schema-traverse@npm:0.4.1" = { filename = "json-schema-traverse-npm-0.4.1-4759091693-7486074d3b.zip"; sha512 = "7486074d3ba247769fda17d5181b345c9fb7d12e0da98b22d1d71a5db9698d8b4bd900a3ec1a4ffdd60846fc2556274a5c894d0c48795f14cb03aeae7b55260b"; };
    "json-schema-traverse@npm:1.0.0" = { filename = "json-schema-traverse-npm-1.0.0-fb3684f4f0-02f2f466cd.zip"; sha512 = "02f2f466cdb0362558b2f1fd5e15cce82ef55d60cd7f8fa828cf35ba74330f8d767fcae5c5c2adb7851fa811766c694b9405810879bc4e1ddd78a7c0e03658ad"; };
    "json-stable-stringify-without-jsonify@npm:1.0.1" = { filename = "json-stable-stringify-without-jsonify-npm-1.0.1-b65772b28b-cff44156dd.zip"; sha512 = "cff44156ddce9c67c44386ad5cddf91925fe06b1d217f2da9c4910d01f358c6e3989c4d5a02683c7a5667f9727ff05831f7aa8ae66c8ff691c556f0884d49215"; };
    "keytar@npm:7.9.0" = { filename = "keytar-npm-7.9.0-682d6e5c1d-4dbdd21f69.zip"; sha512 = "4dbdd21f69e21a53032cbc949847f57338e42df763c5eec04e1b5d7142a689f95d8c3d74fb3b7dc321b5d678271d8d8d1a0dcaa919673ebc50ef8ce76f354e21"; };
    "leven@npm:3.1.0" = { filename = "leven-npm-3.1.0-b7697736a3-638401d534.zip"; sha512 = "638401d534585261b6003db9d99afd244dfe82d75ddb6db5c0df412842d5ab30b2ef18de471aaec70fe69a46f17b4ae3c7f01d8a4e6580ef7adb9f4273ad1e55"; };
    "levn@npm:0.4.1" = { filename = "levn-npm-0.4.1-d183b2d7bb-12c5021c85.zip"; sha512 = "12c5021c859bd0f5248561bf139121f0358285ec545ebf48bb3d346820d5c61a4309535c7f387ed7d84361cf821e124ce346c6b7cef8ee09a67c1473b46d0fc4"; };
    "linkify-it@npm:3.0.3" = { filename = "linkify-it-npm-3.0.3-6880fe29c1-31367a4bb7.zip"; sha512 = "31367a4bb70c5bbc9703246236b504b0a8e049bcd4e0de4291fa50f0ebdebf235b5eb54db6493cb0b1319357c6eeafc4324c9f4aa34b0b943d9f2e11a1268fbc"; };
    "listenercount@npm:1.0.1" = { filename = "listenercount-npm-1.0.1-01172e4210-0f1c9077cd.zip"; sha512 = "0f1c9077cdaf2ebc16473c7d72eb7de6d983898ca42500f03da63c3914b6b312dd5f7a90d2657691ea25adf3fe0ac5a43226e8b2c673fd73415ed038041f4757"; };
    "locate-path@npm:6.0.0" = { filename = "locate-path-npm-6.0.0-06a1e4c528-72eb661788.zip"; sha512 = "72eb661788a0368c099a184c59d2fee760b3831c9c1c33955e8a19ae4a21b4116e53fa736dc086cdeb9fce9f7cc508f2f92d2d3aae516f133e16a2bb59a39f5a"; };
    "lodash.merge@npm:4.6.2" = { filename = "lodash.merge-npm-4.6.2-77cb4416bf-ad580b4bdb.zip"; sha512 = "ad580b4bdbb7ca1f7abf7e1bce63a9a0b98e370cf40194b03380a46b4ed799c9573029599caebc1b14e3f24b111aef72b96674a56cfa105e0f5ac70546cdc005"; };
    "lodash.truncate@npm:4.4.2" = { filename = "lodash.truncate-npm-4.4.2-bc50fe1663-b463d8a382.zip"; sha512 = "b463d8a382cfb5f0e71c504dcb6f807a7bd379ff1ea216669aa42c52fc28c54e404bfbd96791aa09e6df0de2c1d7b8f1b7f4b1a61f324d38fe98bc535aeee4f5"; };
    "log-symbols@npm:4.0.0" = { filename = "log-symbols-npm-4.0.0-7291c4d053-a7c1fb5cc5.zip"; sha512 = "a7c1fb5cc504ff04422460dcae3a830002426432fbed81280c8a49f4c6f5ef244c28b987636bf1c871ba6866d7024713388be391e92c0d5af6a70598fcabc46b"; };
    "lru-cache@npm:6.0.0" = { filename = "lru-cache-npm-6.0.0-b4c8668fe1-f97f499f89.zip"; sha512 = "f97f499f898f23e4585742138a22f22526254fdba6d75d41a1c2526b3b6cc5747ef59c5612ba7375f42aca4f8461950e925ba08c991ead0651b4918b7c978297"; };
    "lru-cache@npm:7.14.1" = { filename = "lru-cache-npm-7.14.1-d3ba9407b6-d72c6713c6.zip"; sha512 = "d72c6713c6a6d86836a7a6523b3f1ac6764768cca47ec99341c3e76db06aacd4764620e5e2cda719a36848785a52a70e531822dc2b33fb071fa709683746c104"; };
    "make-fetch-happen@npm:10.2.1" = { filename = "make-fetch-happen-npm-10.2.1-f1cc7cd2df-2332eb9a8e.zip"; sha512 = "2332eb9a8ec96f1ffeeea56ccefabcb4193693597b132cd110734d50f2928842e22b84cfa1508e921b8385cdfd06dda9ad68645fed62b50fff629a580f5fb72c"; };
    "markdown-it@npm:12.3.2" = { filename = "markdown-it-npm-12.3.2-6c66b716e8-890555711c.zip"; sha512 = "890555711c1c00fa03b936ca2b213001a3b9b37dea140d8445ae4130ce16628392aad24b12e2a0a9935336ca5951f2957a38f4e5309a2e38eab44e25ff32a41e"; };
    "mdurl@npm:1.0.1" = { filename = "mdurl-npm-1.0.1-054d974269-71731ecba9.zip"; sha512 = "71731ecba943926bfbf9f9b51e28b5945f9411c4eda80894221b47cc105afa43ba2da820732b436f0798fd3edbbffcd1fc1415843c41a87fea08a41cc1e3d02b"; };
    "merge2@npm:1.4.1" = { filename = "merge2-npm-1.4.1-a2507bd06c-7268db63ed.zip"; sha512 = "7268db63ed5169466540b6fb947aec313200bcf6d40c5ab722c22e242f651994619bcd85601602972d3c85bd2cc45a358a4c61937e9f11a061919a1da569b0c2"; };
    "micromatch@npm:4.0.5" = { filename = "micromatch-npm-4.0.5-cfab5d7669-02a17b671c.zip"; sha512 = "02a17b671c06e8fefeeb6ef996119c1e597c942e632a21ef589154f23898c9c6a9858526246abb14f8bca6e77734aa9dcf65476fca47cedfb80d9577d52843fc"; };
    "mime@npm:1.6.0" = { filename = "mime-npm-1.6.0-60ae95038a-fef25e3926.zip"; sha512 = "fef25e39263e6d207580bdc629f8872a3f9772c923c7f8c7e793175cee22777bbe8bba95e5d509a40aaa292d8974514ce634ae35769faa45f22d17edda5e8557"; };
    "mimic-response@npm:3.1.0" = { filename = "mimic-response-npm-3.1.0-a4a24b4e96-25739fee32.zip"; sha512 = "25739fee32c17f433626bf19f016df9036b75b3d84a3046c7d156e72ec963dd29d7fc8a302f55a3d6c5a4ff24259676b15d915aad6480815a969ff2ec0836867"; };
    "minimatch@npm:3.0.4" = { filename = "minimatch-npm-3.0.4-6e76f51c23-66ac295f8a.zip"; sha512 = "66ac295f8a7b59788000ea3749938b0970344c841750abd96694f80269b926ebcafad3deeb3f1da2522978b119e6ae3a5869b63b13a7859a456b3408bd18a078"; };
    "minimatch@npm:3.1.2" = { filename = "minimatch-npm-3.1.2-9405269906-c154e56640.zip"; sha512 = "c154e566406683e7bcb746e000b84d74465b3a832c45d59912b9b55cd50dee66e5c4b1e5566dba26154040e51672f9aa450a9aef0c97cfc7336b78b7afb9540a"; };
    "minimatch@npm:5.1.0" = { filename = "minimatch-npm-5.1.0-34f6240621-15ce53d31a.zip"; sha512 = "15ce53d31a06361e8b7a629501b5c75491bc2b59712d53e802b1987121d91b433d73fcc5be92974fde66b2b51d8fb28d75a9ae900d249feb792bb1ba2a4f0a90"; };
    "minimist@npm:1.2.7" = { filename = "minimist-npm-1.2.7-51d33b1371-7346574a10.zip"; sha512 = "7346574a1038ca23c32e02252f603801f09384dd1d78b69a943a4e8c2c28730b80e96193882d3d3b22a063445f460e48316b29b8a25addca2d7e5e8f75478bec"; };
    "minipass-collect@npm:1.0.2" = { filename = "minipass-collect-npm-1.0.2-3b4676eab5-14df761028.zip"; sha512 = "14df761028f3e47293aee72888f2657695ec66bd7d09cae7ad558da30415fdc4752bbfee66287dcc6fd5e6a2fa3466d6c484dc1cbd986525d9393b9523d97f10"; };
    "minipass-fetch@npm:2.1.2" = { filename = "minipass-fetch-npm-2.1.2-9b21a5c930-3f216be791.zip"; sha512 = "3f216be79164e915fc91210cea1850e488793c740534985da017a4cbc7a5ff50506956d0f73bb0cb60e4fe91be08b6b61ef35101706d3ef5da2c8709b5f08f91"; };
    "minipass-flush@npm:1.0.5" = { filename = "minipass-flush-npm-1.0.5-efe79d9826-56269a0b22.zip"; sha512 = "56269a0b22bad756a08a94b1ffc36b7c9c5de0735a4dd1ab2b06c066d795cfd1f0ac44a0fcae13eece5589b908ecddc867f04c745c7009be0b566421ea0944cf"; };
    "minipass-pipeline@npm:1.2.4" = { filename = "minipass-pipeline-npm-1.2.4-5924cb077f-b14240dac0.zip"; sha512 = "b14240dac0d29823c3d5911c286069e36d0b81173d7bdf07a7e4a91ecdef92cdff4baaf31ea3746f1c61e0957f652e641223970870e2353593f382112257971b"; };
    "minipass-sized@npm:1.0.3" = { filename = "minipass-sized-npm-1.0.3-306d86f432-79076749fc.zip"; sha512 = "79076749fcacf21b5d16dd596d32c3b6bf4d6e62abb43868fac21674078505c8b15eaca4e47ed844985a4514854f917d78f588fcd029693709417d8f98b2bd60"; };
    "minipass@npm:3.3.6" = { filename = "minipass-npm-3.3.6-b8d93a945b-a30d083c80.zip"; sha512 = "a30d083c8054cee83cdcdc97f97e4641a3f58ae743970457b1489ce38ee1167b3aaf7d815cd39ec7a99b9c40397fd4f686e83750e73e652b21cb516f6d845e48"; };
    "minizlib@npm:2.1.2" = { filename = "minizlib-npm-2.1.2-ea89cd0cfb-f1fdeac0b0.zip"; sha512 = "f1fdeac0b07cf8f30fcf12f4b586795b97be856edea22b5e9072707be51fc95d41487faec3f265b42973a304fe3a64acd91a44a3826a963e37b37bafde0212c3"; };
    "mkdirp-classic@npm:0.5.3" = { filename = "mkdirp-classic-npm-0.5.3-3b5c991910-3f4e088208.zip"; sha512 = "3f4e088208270bbcc148d53b73e9a5bd9eef05ad2cbf3b3d0ff8795278d50dd1d11a8ef1875ff5aea3fa888931f95bfcb2ad5b7c1061cfefd6284d199e6776ac"; };
    "mkdirp@npm:0.5.6" = { filename = "mkdirp-npm-0.5.6-dcd5a6b97b-0c91b721bb.zip"; sha512 = "0c91b721bb12c3f9af4b77ebf73604baf350e64d80df91754dc509491ae93bf238581e59c7188360cec7cb62fc4100959245a42cfe01834efedc5e9d068376c2"; };
    "mkdirp@npm:1.0.4" = { filename = "mkdirp-npm-1.0.4-37f6ef56b9-a96865108c.zip"; sha512 = "a96865108c6c3b1b8e1d5e9f11843de1e077e57737602de1b82030815f311be11f96f09cce59bd5b903d0b29834733e5313f9301e3ed6d6f6fba2eae0df4298f"; };
    "mocha@npm:8.4.0" = { filename = "mocha-npm-8.4.0-a999d05791-4bcf006705.zip"; sha512 = "4bcf00670580f009f9e20cc596cce5e2434d3562c468da783a8f935e38c4476435f12ecade43341cb8730b9d4987358038e76a075201d4bc51010927d3f8cd7c"; };
    "ms@npm:2.1.2" = { filename = "ms-npm-2.1.2-ec0c1512ff-673cdb2c31.zip"; sha512 = "673cdb2c3133eb050c745908d8ce632ed2c02d85640e2edb3ace856a2266a813b30c613569bf3354fdf4ea7d1a1494add3bfa95e2713baa27d0c2c71fc44f58f"; };
    "ms@npm:2.1.3" = { filename = "ms-npm-2.1.3-81ff3cfac1-aa92de6080.zip"; sha512 = "aa92de608021b242401676e35cfa5aa42dd70cbdc082b916da7fb925c542173e36bce97ea3e804923fe92c0ad991434e4a38327e15a1b5b5f945d66df615ae6d"; };
    "mute-stream@npm:0.0.8" = { filename = "mute-stream-npm-0.0.8-489a7d6c2b-ff48d251fc.zip"; sha512 = "ff48d251fc3f827e5b1206cda0ffdaec885e56057ee86a3155e1951bc940fd5f33531774b1cc8414d7668c10a8907f863f6561875ee6e8768931a62121a531a1"; };
    "nanoid@npm:3.1.20" = { filename = "nanoid-npm-3.1.20-3b284e9eb5-f6246023d5.zip"; sha512 = "f6246023d5d8313c2c16be05c18cdb189a6de50ab6418b513b34086eda4aabd12866b2cbe435548c760dc43cf11830b26b14b113afde47305398e3345795e433"; };
    "napi-build-utils@npm:1.0.2" = { filename = "napi-build-utils-npm-1.0.2-892e4bba56-06c14271ee.zip"; sha512 = "06c14271ee966e108d55ae109f340976a9556c8603e888037145d6522726aebe89dd0c861b4b83947feaf6d39e79e08817559e8693deedc2c94e82c5cbd090c7"; };
    "natural-compare@npm:1.4.0" = { filename = "natural-compare-npm-1.4.0-97b75b362d-23ad088b08.zip"; sha512 = "23ad088b08f898fc9b53011d7bb78ec48e79de7627e01ab5518e806033861bef68d5b0cd0e2205c2f36690ac9571ff6bcb05eb777ced2eeda8d4ac5b44592c3d"; };
    "negotiator@npm:0.6.3" = { filename = "negotiator-npm-0.6.3-9d50e36171-b8ffeb1e26.zip"; sha512 = "b8ffeb1e262eff7968fc90a2b6767b04cfd9842582a9d0ece0af7049537266e7b2506dfb1d107a32f06dd849ab2aea834d5830f7f4d0e5cb7d36e1ae55d021d9"; };
    "node-abi@npm:3.28.0" = { filename = "node-abi-npm-3.28.0-7291733a57-ed8db5e58f.zip"; sha512 = "ed8db5e58fc9e1400a3f74d8815b6981208a4fca2031e2c5f5986f58f7e3a1f4161dae82c655f9114892b3f46c21c02feec10fbac0f8ffcfd26a3d57447093d1"; };
    "node-addon-api@npm:4.3.0" = { filename = "node-addon-api-npm-4.3.0-a07a1232df-3de396e23c.zip"; sha512 = "3de396e23cc209f539c704583e8e99c148850226f6e389a641b92e8967953713228109f919765abc1f4355e801e8f41842f96210b8d61c7dcc10a477002dcf00"; };
    "node-gyp@npm:9.3.0" = { filename = "node-gyp-npm-9.3.0-21c41a4dfd-589ddd3ed9.zip"; sha512 = "589ddd3ed967724ef425f9624bfa47cf73022640ab3eba6d556e92cdc4ddef33b63fce3a467c93b995a3f61df92eafd3c3d1e8dbe4a2c00c383334487dea99c3"; };
    "nopt@npm:6.0.0" = { filename = "nopt-npm-6.0.0-5ea8050815-82149371f8.zip"; sha512 = "82149371f8be0c4b9ec2f863cc6509a7fd0fa729929c009f3a58e4eb0c9e4cae9920e8f1f8eb46e7d032fec8fb01bede7f0f41a67eb3553b7b8e14fa53de1dac"; };
    "normalize-path@npm:3.0.0" = { filename = "normalize-path-npm-3.0.0-658ba7d77f-88eeb4da89.zip"; sha512 = "88eeb4da891e10b1318c4b2476b6e2ecbeb5ff97d946815ffea7794c31a89017c70d7f34b3c2ebf23ef4e9fc9fb99f7dffe36da22011b5b5c6ffa34f4873ec20"; };
    "npmlog@npm:6.0.2" = { filename = "npmlog-npm-6.0.2-e0e69455c7-ae238cd264.zip"; sha512 = "ae238cd264a1c3f22091cdd9e2b106f684297d3c184f1146984ecbe18aaa86343953f26b9520dedd1b1372bc0316905b736c1932d778dbeb1fcf5a1001390e2a"; };
    "nth-check@npm:2.1.1" = { filename = "nth-check-npm-2.1.1-f97afc8169-5afc3dafcd.zip"; sha512 = "5afc3dafcd1573b08877ca8e6148c52abd565f1d06b1eb08caf982e3fa289a82f2cae697ffb55b5021e146d60443f1590a5d6b944844e944714a5b549675bcd3"; };
    "object-inspect@npm:1.12.2" = { filename = "object-inspect-npm-1.12.2-f125a822c0-a534fc1b85.zip"; sha512 = "a534fc1b8534284ed71f25ce3a496013b7ea030f3d1b77118f6b7b1713829262be9e6243acbcb3ef8c626e2b64186112cb7f6db74e37b2789b9c789ca23048b2"; };
    "once@npm:1.4.0" = { filename = "once-npm-1.4.0-ccf03ef07a-cd0a885013.zip"; sha512 = "cd0a88501333edd640d95f0d2700fbde6bff20b3d4d9bdc521bdd31af0656b5706570d6c6afe532045a20bb8dc0849f8332d6f2a416e0ba6d3d3b98806c7db68"; };
    "optionator@npm:0.9.1" = { filename = "optionator-npm-0.9.1-577e397aae-dbc6fa0656.zip"; sha512 = "dbc6fa065604b24ea57d734261914e697bd73b69eff7f18e967e8912aa2a40a19a9f599a507fa805be6c13c24c4eae8c71306c239d517d42d4c041c942f508a0"; };
    "p-limit@npm:3.1.0" = { filename = "p-limit-npm-3.1.0-05d2ede37f-7c3690c4db.zip"; sha512 = "7c3690c4dbf62ef625671e20b7bdf1cbc9534e83352a2780f165b0d3ceba21907e77ad63401708145ca4e25bfc51636588d89a8c0aeb715e6c37d1c066430360"; };
    "p-locate@npm:5.0.0" = { filename = "p-locate-npm-5.0.0-92cc7c7a3e-1623088f36.zip"; sha512 = "1623088f36cf1cbca58e9b61c4e62bf0c60a07af5ae1ca99a720837356b5b6c5ba3eb1b2127e47a06865fee59dd0453cad7cc844cda9d5a62ac1a5a51b7c86d3"; };
    "p-map@npm:4.0.0" = { filename = "p-map-npm-4.0.0-4677ae07c7-cb0ab21ec0.zip"; sha512 = "cb0ab21ec0f32ddffd31dfc250e3afa61e103ef43d957cc45497afe37513634589316de4eb88abdfd969fe6410c22c0b93ab24328833b8eb1ccc087fc0442a1c"; };
    "parent-module@npm:1.0.1" = { filename = "parent-module-npm-1.0.1-1fae11b095-6ba8b25514.zip"; sha512 = "6ba8b255145cae9470cf5551eb74be2d22281587af787a2626683a6c20fbb464978784661478dd2a3f1dad74d1e802d403e1b03c1a31fab310259eec8ac560ff"; };
    "parse-semver@npm:1.1.1" = { filename = "parse-semver-npm-1.1.1-45d28f8138-0a9abc24b8.zip"; sha512 = "0a9abc24b829b4db6dfd733727c2dd15b085c388b7c0bcc03e801412c1ebfe53a087613240f90af0dbed3a3283057bd320014b0df4b9222e01b4e3757b5c6e6a"; };
    "parse5-htmlparser2-tree-adapter@npm:7.0.0" = { filename = "parse5-htmlparser2-tree-adapter-npm-7.0.0-38e1b3a974-fc5d01e077.zip"; sha512 = "fc5d01e07733142a1baf81de5c2a9c41426c04b7ab29dd218acb80cd34a63177c90aff4a4aee66cf9f1d0aeecff1389adb7452ad6f8af0a5888e3e9ad6ef733d"; };
    "parse5@npm:7.1.2" = { filename = "parse5-npm-7.1.2-aa9a92c270-59465dd05e.zip"; sha512 = "59465dd05eb4c5ec87b76173d1c596e152a10e290b7abcda1aecf0f33be49646ea74840c69af975d7887543ea45564801736356c568d6b5e71792fd0f4055713"; };
    "path-exists@npm:4.0.0" = { filename = "path-exists-npm-4.0.0-e9e4f63eb0-505807199d.zip"; sha512 = "505807199dfb7c50737b057dd8d351b82c033029ab94cb10a657609e00c1bc53b951cfdbccab8de04c5584d5eff31128ce6afd3db79281874a5ef2adbba55ed1"; };
    "path-is-absolute@npm:1.0.1" = { filename = "path-is-absolute-npm-1.0.1-31bc695ffd-060840f92c.zip"; sha512 = "060840f92cf8effa293bcc1bea81281bd7d363731d214cbe5c227df207c34cd727430f70c6037b5159c8a870b9157cba65e775446b0ab06fd5ecc7e54615a3b8"; };
    "path-key@npm:3.1.1" = { filename = "path-key-npm-3.1.1-0e66ea8321-55cd7a9dd4.zip"; sha512 = "55cd7a9dd4b343412a8386a743f9c746ef196e57c823d90ca3ab917f90ab9f13dd0ded27252ba49dbdfcab2b091d998bc446f6220cd3cea65db407502a740020"; };
    "path-type@npm:4.0.0" = { filename = "path-type-npm-4.0.0-10d47fc86a-5b1e2daa24.zip"; sha512 = "5b1e2daa247062061325b8fdbfd1fb56dde0a448fb1455453276ea18c60685bdad23a445dc148cf87bc216be1573357509b7d4060494a6fd768c7efad833ee45"; };
    "pend@npm:1.2.0" = { filename = "pend-npm-1.2.0-7a13d93266-6c72f52433.zip"; sha512 = "6c72f5243303d9c60bd98e6446ba7d30ae29e3d56fdb6fae8767e8ba6386f33ee284c97efe3230a0d0217e2b1723b8ab490b1bbf34fcbb2180dbc8a9de47850d"; };
    "picomatch@npm:2.3.1" = { filename = "picomatch-npm-2.3.1-c782cfd986-050c865ce8.zip"; sha512 = "050c865ce81119c4822c45d3c84f1ced46f93a0126febae20737bd05ca20589c564d6e9226977df859ed5e03dc73f02584a2b0faad36e896936238238b0446cf"; };
    "prebuild-install@npm:7.1.1" = { filename = "prebuild-install-npm-7.1.1-cb9fc9d341-dbf96d0146.zip"; sha512 = "dbf96d0146b6b5827fc8f67f72074d2e19c69628b9a7a0a17d0fad1bf37e9f06922896972e074197fc00a52eae912993e6ef5a0d471652f561df5cb516f3f467"; };
    "prelude-ls@npm:1.2.1" = { filename = "prelude-ls-npm-1.2.1-3e4d272a55-cd192ec0d0.zip"; sha512 = "cd192ec0d0a8e4c6da3bb80e4f62afe336df3f76271ac6deb0e6a36187133b6073a19e9727a1ff108cd8b9982e4768850d413baa71214dd80c7979617dca827a"; };
    "process-nextick-args@npm:2.0.1" = { filename = "process-nextick-args-npm-2.0.1-b8d7971609-1d38588e52.zip"; sha512 = "1d38588e520dab7cea67cbbe2efdd86a10cc7a074c09657635e34f035277b59fbb57d09d8638346bf7090f8e8ebc070c96fa5fd183b777fff4f5edff5e9466cf"; };
    "progress@npm:2.0.3" = { filename = "progress-npm-2.0.3-d1f87e2ac6-f67403fe7b.zip"; sha512 = "f67403fe7b34912148d9252cb7481266a354bd99ce82c835f79070643bb3c6583d10dbcfda4d41e04bbc1d8437e9af0fb1e1f2135727878f5308682a579429b7"; };
    "promise-inflight@npm:1.0.1" = { filename = "promise-inflight-npm-1.0.1-5bb925afac-2274948309.zip"; sha512 = "22749483091d2c594261517f4f80e05226d4d5ecc1fc917e1886929da56e22b5718b7f2a75f3807e7a7d471bc3be2907fe92e6e8f373ddf5c64bae35b5af3981"; };
    "promise-retry@npm:2.0.1" = { filename = "promise-retry-npm-2.0.1-871f0b01b7-f96a3f6d90.zip"; sha512 = "f96a3f6d90b92b568a26f71e966cbbc0f63ab85ea6ff6c81284dc869b41510e6cdef99b6b65f9030f0db422bf7c96652a3fff9f2e8fb4a0f069d8f4430359429"; };
    "pump@npm:3.0.0" = { filename = "pump-npm-3.0.0-0080bf6a7a-e42e9229fb.zip"; sha512 = "e42e9229fba14732593a718b04cb5e1cfef8254544870997e0ecd9732b189a48e1256e4e5478148ecb47c8511dca2b09eae56b4d0aad8009e6fac8072923cfc9"; };
    "punycode@npm:2.1.1" = { filename = "punycode-npm-2.1.1-26eb3e15cf-823bf443c6.zip"; sha512 = "823bf443c6dd14f669984dea25757b37993f67e8d94698996064035edd43bed8a5a17a9f12e439c2b35df1078c6bec05a6c86e336209eb1061e8025c481168e8"; };
    "qs@npm:6.11.0" = { filename = "qs-npm-6.11.0-caf1bc9dea-6e1f29dd53.zip"; sha512 = "6e1f29dd5385f7488ec74ac7b6c92f4d09a90408882d0c208414a34dd33badc1a621019d4c799a3df15ab9b1d0292f97c1dd71dc7c045e69f81a8064e5af7297"; };
    "queue-microtask@npm:1.2.3" = { filename = "queue-microtask-npm-1.2.3-fcc98e4e2d-b676f8c040.zip"; sha512 = "b676f8c040cdc5b12723ad2f91414d267605b26419d5c821ff03befa817ddd10e238d22b25d604920340fd73efd8ba795465a0377c4adf45a4a41e4234e42dc4"; };
    "randombytes@npm:2.1.0" = { filename = "randombytes-npm-2.1.0-e3da76bccf-d779499376.zip"; sha512 = "d779499376bd4cbb435ef3ab9a957006c8682f343f14089ed5f27764e4645114196e75b7f6abf1cbd84fd247c0cb0651698444df8c9bf30e62120fbbc52269d6"; };
    "rc@npm:1.2.8" = { filename = "rc-npm-1.2.8-d6768ac936-2e26e052f8.zip"; sha512 = "2e26e052f8be2abd64e6d1dabfbd7be03f80ec18ccbc49562d31f617d0015fbdbcf0f9eed30346ea6ab789e0fdfe4337f033f8016efdbee0df5354751842080e"; };
    "read@npm:1.0.7" = { filename = "read-npm-1.0.7-950ec74ca8-2777c254e5.zip"; sha512 = "2777c254e5732cac96f5d0a1c0f6b836c89ae23d8febd405b206f6f24d5de1873420f1a0795e0e3721066650d19adf802c7882c4027143ee0acf942a4f34f97b"; };
    "readable-stream@npm:2.3.7" = { filename = "readable-stream-npm-2.3.7-77b22a9818-e4920cf754.zip"; sha512 = "e4920cf7549a60f8aaf694d483a0e61b2a878b969d224f89b3bc788b8d920075132c4b55a7494ee944c7b6a9a0eada28a7f6220d80b0312ece70bbf08eeca755"; };
    "readable-stream@npm:3.6.0" = { filename = "readable-stream-npm-3.6.0-23a4a5eb56-d4ea81502d.zip"; sha512 = "d4ea81502d3799439bb955a3a5d1d808592cf3133350ed352aeaa499647858b27b1c4013984900238b0873ec8d0d8defce72469fb7a83e61d53f5ad61cb80dc8"; };
    "readdirp@npm:3.5.0" = { filename = "readdirp-npm-3.5.0-a1b1568d32-6b1a9341e2.zip"; sha512 = "6b1a9341e295e15d4fb40c010216cbcb6266587cd0b3ce7defabd66fa1b4e35f9fba3d64c2187fd38fadd01ccbfc5f1b33fdfb1da63b3cbf66224b7c6d75ce5a"; };
    "regexpp@npm:3.2.0" = { filename = "regexpp-npm-3.2.0-2513f32cfc-a78dc5c715.zip"; sha512 = "a78dc5c7158ad9ddcfe01aa9144f46e192ddbfa7b263895a70a5c6c73edd9ce85faf7c0430e59ac38839e1734e275b9c3de5c57ee3ab6edc0e0b1bdebefccef8"; };
    "require-directory@npm:2.1.1" = { filename = "require-directory-npm-2.1.1-8608aee50b-fb47e70bf0.zip"; sha512 = "fb47e70bf0001fdeabdc0429d431863e9475e7e43ea5f94ad86503d918423c1543361cc5166d713eaa7029dd7a3d34775af04764bebff99ef413111a5af18c80"; };
    "require-from-string@npm:2.0.2" = { filename = "require-from-string-npm-2.0.2-8557e0db12-a03ef68954.zip"; sha512 = "a03ef6895445f33a4015300c426699bc66b2b044ba7b670aa238610381b56d3f07c686251740d575e22f4c87531ba662d06937508f0f3c0f1ddc04db3130560b"; };
    "resolve-from@npm:4.0.0" = { filename = "resolve-from-npm-4.0.0-f758ec21bf-f4ba0b8494.zip"; sha512 = "f4ba0b8494846a5066328ad33ef8ac173801a51739eb4d63408c847da9a2e1c1de1e6cbbf72699211f3d13f8fc1325648b169bd15eb7da35688e30a5fb0e4a7f"; };
    "retry@npm:0.12.0" = { filename = "retry-npm-0.12.0-72ac7fb4cc-623bd7d2e5.zip"; sha512 = "623bd7d2e5119467ba66202d733ec3c2e2e26568074923bc0585b6b99db14f357e79bdedb63cab56cec47491c4a0da7e6021a7465ca6dc4f481d3898fdd3158c"; };
    "reusify@npm:1.0.4" = { filename = "reusify-npm-1.0.4-95ac4aec11-c3076ebcc2.zip"; sha512 = "c3076ebcc22a6bc252cb0b9c77561795256c22b757f40c0d8110b1300723f15ec0fc8685e8d4ea6d7666f36c79ccc793b1939c748bf36f18f542744a4e379fcc"; };
    "rimraf@npm:2.7.1" = { filename = "rimraf-npm-2.7.1-9a71f3cc37-cdc7f6eacb.zip"; sha512 = "cdc7f6eacb17927f2a075117a823e1c5951792c6498ebcce81ca8203454a811d4cf8900314154d3259bb8f0b42ab17f67396a8694a54cae3283326e57ad250cd"; };
    "rimraf@npm:3.0.2" = { filename = "rimraf-npm-3.0.2-2cb7dac69a-87f4164e39.zip"; sha512 = "87f4164e396f0171b0a3386cc1877a817f572148ee13a7e113b238e48e8a9f2f31d009a92ec38a591ff1567d9662c6b67fd8818a2dbbaed74bc26a87a2a4a9a0"; };
    "run-parallel@npm:1.2.0" = { filename = "run-parallel-npm-1.2.0-3f47ff2034-cb4f97ad25.zip"; sha512 = "cb4f97ad25a75ebc11a8ef4e33bb962f8af8516bb2001082ceabd8902e15b98f4b84b4f8a9b222e5d57fc3bd1379c483886ed4619367a7680dad65316993021d"; };
    "safe-buffer@npm:5.1.2" = { filename = "safe-buffer-npm-5.1.2-c27fedf6c4-f2f1f7943c.zip"; sha512 = "f2f1f7943ca44a594893a852894055cf619c1fbcb611237fc39e461ae751187e7baf4dc391a72125e0ac4fb2d8c5c0b3c71529622e6a58f46b960211e704903c"; };
    "safe-buffer@npm:5.2.1" = { filename = "safe-buffer-npm-5.2.1-3481c8aa9b-b99c4b41fd.zip"; sha512 = "b99c4b41fdd67a6aaf280fcd05e9ffb0813654894223afb78a31f14a19ad220bba8aba1cb14eddce1fcfb037155fe6de4e861784eb434f7d11ed58d1e70dd491"; };
    "safer-buffer@npm:2.1.2" = { filename = "safer-buffer-npm-2.1.2-8d5c0b705e-cab8f25ae6.zip"; sha512 = "cab8f25ae6f1434abee8d80023d7e72b598cf1327164ddab31003c51215526801e40b66c5e65d658a0af1e9d6478cadcb4c745f4bd6751f97d8644786c0978b0"; };
    "sax@npm:1.2.4" = { filename = "sax-npm-1.2.4-178f05f12f-d3df7d32b8.zip"; sha512 = "d3df7d32b897a2c2f28e941f732c71ba90e27c24f62ee918bd4d9a8cfb3553f2f81e5493c7f0be94a11c1911b643a9108f231dd6f60df3fa9586b5d2e3e9e1fe"; };
    "semver@npm:5.7.1" = { filename = "semver-npm-5.7.1-40bcea106b-57fd0acfd0.zip"; sha512 = "57fd0acfd0bac382ee87cd52cd0aaa5af086a7dc8d60379dfe65fea491fb2489b6016400813930ecd61fd0952dae75c115287a1b16c234b1550887117744dfaf"; };
    "semver@npm:7.3.8" = { filename = "semver-npm-7.3.8-25a996cb4f-ba9c7cbbf2.zip"; sha512 = "ba9c7cbbf2b7884696523450a61fee1a09930d888b7a8d7579025ad93d459b2d1949ee5bbfeb188b2be5f4ac163544c5e98491ad6152df34154feebc2cc337c1"; };
    "serialize-javascript@npm:5.0.1" = { filename = "serialize-javascript-npm-5.0.1-8ffc173f09-bb45a42769.zip"; sha512 = "bb45a427690c3d2711e28499de0fbf25036af1e23c63c6a9237ed0aa572fd0941fcdefe50a2dccf26d9df8c8b86ae38659e19d8ba7afd3fbc1f1c7539a2a48d2"; };
    "set-blocking@npm:2.0.0" = { filename = "set-blocking-npm-2.0.0-49e2cffa24-6e65a05f7c.zip"; sha512 = "6e65a05f7cf7ebdf8b7c75b101e18c0b7e3dff4940d480efed8aad3a36a4005140b660fa1d804cb8bce911cac290441dc728084a30504d3516ac2ff7ad607b02"; };
    "setimmediate@npm:1.0.5" = { filename = "setimmediate-npm-1.0.5-54587459b6-c9a6f2c5b5.zip"; sha512 = "c9a6f2c5b51a2dabdc0247db9c46460152ffc62ee139f3157440bd48e7c59425093f42719ac1d7931f054f153e2d26cf37dfeb8da17a794a58198a2705e527fd"; };
    "shebang-command@npm:2.0.0" = { filename = "shebang-command-npm-2.0.0-eb2b01921d-6b52fe8727.zip"; sha512 = "6b52fe87271c12968f6a054e60f6bde5f0f3d2db483a1e5c3e12d657c488a15474121a1d55cd958f6df026a54374ec38a4a963988c213b7570e1d51575cea7fa"; };
    "shebang-regex@npm:3.0.0" = { filename = "shebang-regex-npm-3.0.0-899a0cd65e-1a2bcae50d.zip"; sha512 = "1a2bcae50de99034fcd92ad4212d8e01eedf52c7ec7830eedcf886622804fe36884278f2be8be0ea5fde3fd1c23911643a4e0f726c8685b61871c8908af01222"; };
    "side-channel@npm:1.0.4" = { filename = "side-channel-npm-1.0.4-e1f38b9e06-351e41b947.zip"; sha512 = "351e41b947079c10bd0858364f32bb3a7379514c399edb64ab3dce683933483fc63fb5e4efe0a15a2e8a7e3c436b6a91736ddb8d8c6591b0460a24bb4a1ee245"; };
    "signal-exit@npm:3.0.7" = { filename = "signal-exit-npm-3.0.7-bd270458a3-a2f098f247.zip"; sha512 = "a2f098f247adc367dffc27845853e9959b9e88b01cb301658cfe4194352d8d2bb32e18467c786a7fe15f1d44b233ea35633d076d5e737870b7139949d1ab6318"; };
    "simple-concat@npm:1.0.1" = { filename = "simple-concat-npm-1.0.1-48df70de29-4d211042cc.zip"; sha512 = "4d211042cc3d73a718c21ac6c4e7d7a0363e184be6a5ad25c8a1502e49df6d0a0253979e3d50dbdd3f60ef6c6c58d756b5d66ac1e05cda9cacd2e9fc59e3876a"; };
    "simple-get@npm:4.0.1" = { filename = "simple-get-npm-4.0.1-fa2a97645d-e4132fd27c.zip"; sha512 = "e4132fd27cf7af230d853fa45c1b8ce900cb430dd0a3c6d3829649fe4f2b26574c803698076c4006450efb0fad2ba8c5455fbb5755d4b0a5ec42d4f12b31d27e"; };
    "slash@npm:3.0.0" = { filename = "slash-npm-3.0.0-b87de2279a-94a93fff61.zip"; sha512 = "94a93fff615f25a999ad4b83c9d5e257a7280c90a32a7cb8b4a87996e4babf322e469c42b7f649fd5796edd8687652f3fb452a86dc97a816f01113183393f11c"; };
    "slice-ansi@npm:4.0.0" = { filename = "slice-ansi-npm-4.0.0-6eeca1d10e-4a82d7f085.zip"; sha512 = "4a82d7f085b0e1b070e004941ada3c40d3818563ac44766cca4ceadd2080427d337554f9f99a13aaeb3b4a94d9964d9466c807b3d7b7541d1ec37ee32d308756"; };
    "smart-buffer@npm:4.2.0" = { filename = "smart-buffer-npm-4.2.0-5ac3f668bb-b5167a7142.zip"; sha512 = "b5167a7142c1da704c0e3af85c402002b597081dd9575031a90b4f229ca5678e9a36e8a374f1814c8156a725d17008ae3bde63b92f9cfd132526379e580bec8b"; };
    "socks-proxy-agent@npm:7.0.0" = { filename = "socks-proxy-agent-npm-7.0.0-7aacf32ea0-7205543701.zip"; sha512 = "720554370154cbc979e2e9ce6a6ec6ced205d02757d8f5d93fe95adae454fc187a5cbfc6b022afab850a5ce9b4c7d73e0f98e381879cf45f66317a4895953846"; };
    "socks@npm:2.7.1" = { filename = "socks-npm-2.7.1-17f2b53052-259d9e3e8e.zip"; sha512 = "259d9e3e8e1c9809a7f5c32238c3d4d2a36b39b83851d0f573bfde5f21c4b1288417ce1af06af1452569cd1eb0841169afd4998f0e04ba04656f6b7f0e46d748"; };
    "sprintf-js@npm:1.0.3" = { filename = "sprintf-js-npm-1.0.3-73f0a322fa-19d79aec21.zip"; sha512 = "19d79aec211f09b99ec3099b5b2ae2f6e9cdefe50bc91ac4c69144b6d3928a640bb6ae5b3def70c2e85a2c3d9f5ec2719921e3a59d3ca3ef4b2fd1a4656a0df3"; };
    "ssri@npm:9.0.1" = { filename = "ssri-npm-9.0.1-33ce27f4f8-fb58f5e46b.zip"; sha512 = "fb58f5e46b6923ae67b87ad5ef1c5ab6d427a17db0bead84570c2df3cd50b4ceb880ebdba2d60726588272890bae842a744e1ecce5bd2a2a582fccd5068309eb"; };
    "string-width@npm:2.1.1" = { filename = "string-width-npm-2.1.1-0c2c6ae53f-d6173abe08.zip"; sha512 = "d6173abe088c615c8dffaf3861dc5d5906ed3dc2d6fd67ff2bd2e2b5dce7fd683c5240699cf0b1b8aa679a3b3bd6b28b5053c824cb89b813d7f6541d8f89064a"; };
    "string-width@npm:4.2.3" = { filename = "string-width-npm-4.2.3-2c27177bae-e52c10dc3f.zip"; sha512 = "e52c10dc3fbfcd6c3a15f159f54a90024241d0f149cf8aed2982a2d801d2e64df0bf1dc351cf8e95c3319323f9f220c16e740b06faecd53e2462df1d2b5443fb"; };
    "string_decoder@npm:1.1.1" = { filename = "string_decoder-npm-1.1.1-e46a6c1353-9ab7e56f9d.zip"; sha512 = "9ab7e56f9d60a28f2be697419917c50cac19f3e8e6c28ef26ed5f4852289fe0de5d6997d29becf59028556f2c62983790c1d9ba1e2a3cc401768ca12d5183a5b"; };
    "string_decoder@npm:1.3.0" = { filename = "string_decoder-npm-1.3.0-2422117fd0-8417646695.zip"; sha512 = "8417646695a66e73aefc4420eb3b84cc9ffd89572861fe004e6aeb13c7bc00e2f616247505d2dbbef24247c372f70268f594af7126f43548565c68c117bdeb56"; };
    "strip-ansi@npm:4.0.0" = { filename = "strip-ansi-npm-4.0.0-d4de985014-d9186e6c0c.zip"; sha512 = "d9186e6c0cf78f25274f6750ee5e4a5725fb91b70fdd79aa5fe648eab092a0ec5b9621b22d69d4534a56319f75d8944efbd84e3afa8d4ad1b9a9491f12c84eca"; };
    "strip-ansi@npm:6.0.1" = { filename = "strip-ansi-npm-6.0.1-caddc7cb40-f3cd25890a.zip"; sha512 = "f3cd25890aef3ba6e1a74e20896c21a46f482e93df4a06567cebf2b57edabb15133f1f94e57434e0a958d61186087b1008e89c94875d019910a213181a14fc8c"; };
    "strip-json-comments@npm:2.0.1" = { filename = "strip-json-comments-npm-2.0.1-e7883b2d04-1074ccb632.zip"; sha512 = "1074ccb63270d32ca28edfb0a281c96b94dc679077828135141f27d52a5a398ef5e78bcf22809d23cadc2b81dfbe345eb5fd8699b385c8b1128907dec4a7d1e1"; };
    "strip-json-comments@npm:3.1.1" = { filename = "strip-json-comments-npm-3.1.1-dcb2324823-492f73e272.zip"; sha512 = "492f73e27268f9b1c122733f28ecb0e7e8d8a531a6662efbd08e22cccb3f9475e90a1b82cab06a392f6afae6d2de636f977e231296400d0ec5304ba70f166443"; };
    "supports-color@npm:5.5.0" = { filename = "supports-color-npm-5.5.0-183ac537bc-95f6f4ba5a.zip"; sha512 = "95f6f4ba5afdf92f495b5a912d4abee8dcba766ae719b975c56c084f5004845f6f5a5f7769f52d53f40e21952a6d87411bafe34af4a01e65f9926002e38e1dac"; };
    "supports-color@npm:7.2.0" = { filename = "supports-color-npm-7.2.0-606bfcf7da-3dda818de0.zip"; sha512 = "3dda818de06ebbe5b9653e07842d9479f3555ebc77e9a0280caf5a14fb877ffee9ed57007c3b78f5a6324b8dbeec648d9e97a24e2ed9fdb81ddc69ea07100f4a"; };
    "supports-color@npm:8.1.1" = { filename = "supports-color-npm-8.1.1-289e937149-c052193a7e.zip"; sha512 = "c052193a7e43c6cdc741eb7f378df605636e01ad434badf7324f17fb60c69a880d8d8fcdcb562cf94c2350e57b937d7425ab5b8326c67c2adc48f7c87c1db406"; };
    "table@npm:6.8.1" = { filename = "table-npm-6.8.1-83abb79e20-08249c7046.zip"; sha512 = "08249c7046125d9d0a944a6e96cfe9ec66908d6b8a9db125531be6eb05fa0de047fd5542e9d43b4f987057f00a093b276b8d3e19af162a9c40db2681058fd306"; };
    "tar-fs@npm:2.1.1" = { filename = "tar-fs-npm-2.1.1-e374d3b7a2-f5b9a70059.zip"; sha512 = "f5b9a70059f5b2969e65f037b4e4da2daf0fa762d3d232ffd96e819e3f94665dbbbe62f76f084f1acb4dbdcce16c6e4dac08d12ffc6d24b8d76720f4d9cf032d"; };
    "tar-stream@npm:2.2.0" = { filename = "tar-stream-npm-2.2.0-884c79b510-699831a8b9.zip"; sha512 = "699831a8b97666ef50021c767f84924cfee21c142c2eb0e79c63254e140e6408d6d55a065a2992548e72b06de39237ef2b802b99e3ece93ca3904a37622a66f3"; };
    "tar@npm:6.1.12" = { filename = "tar-npm-6.1.12-c7d6bb4891-49d72e4420.zip"; sha512 = "49d72e4420944e7ede2782d6b0826a6ede6cdab23c7de63470917e7a78166bc4d5b1a96279d3d79a85f1ba5a17cd37c0acbb3cbff19a07447691445b8b051c55"; };
    "text-table@npm:0.2.0" = { filename = "text-table-npm-0.2.0-d92a778b59-b6937a38c8.zip"; sha512 = "b6937a38c80c7f84d9c11dd75e49d5c44f71d95e810a3250bd1f1797fc7117c57698204adf676b71497acc205d769d65c16ae8fa10afad832ae1322630aef10a"; };
    "tmp@npm:0.2.1" = { filename = "tmp-npm-0.2.1-a9c8d9c0ca-8b12146541.zip"; sha512 = "8b1214654182575124498c87ca986ac53dc76ff36e8f0e0b67139a8d221eaecfdec108c0e6ec54d76f49f1f72ab9325500b246f562b926f85bcdfca8bf35df9e"; };
    "to-regex-range@npm:5.0.1" = { filename = "to-regex-range-npm-5.0.1-f1e8263b00-f76fa01b3d.zip"; sha512 = "f76fa01b3d5be85db6a2a143e24df9f60dd047d151062d0ba3df62953f2f697b16fe5dad9b0ac6191c7efc7b1d9dcaa4b768174b7b29da89d4428e64bc0a20ed"; };
    "traverse@npm:0.3.9" = { filename = "traverse-npm-0.3.9-913743c694-982982e4e2.zip"; sha512 = "982982e4e249e9bbf063732a41fe5595939892758524bbef5d547c67cdf371b13af72b5434c6a61d88d4bb4351d6dabc6e22d832e0d16bc1bc684ef97a1cc59e"; };
    "tslib@npm:1.14.1" = { filename = "tslib-npm-1.14.1-102499115e-dbe628ef87.zip"; sha512 = "dbe628ef87f66691d5d2959b3e41b9ca0045c3ee3c7c7b906cc1e328b39f199bb1ad9e671c39025bd56122ac57dfbf7385a94843b1cc07c60a4db74795829acd"; };
    "tsutils@npm:3.21.0" = { filename = "tsutils-npm-3.21.0-347e6636c5-1843f4c1b2.zip"; sha512 = "1843f4c1b2e0f975e08c4c21caa4af4f7f65a12ac1b81b3b8489366826259323feb3fc7a243123453d2d1a02314205a7634e048d4a8009921da19f99755cdc48"; };
    "tunnel-agent@npm:0.6.0" = { filename = "tunnel-agent-npm-0.6.0-64345ab7eb-05f6510358.zip"; sha512 = "05f6510358f8afc62a057b8b692f05d70c1782b70db86d6a1e0d5e28a32389e52fa6e7707b6c5ecccacc031462e4bc35af85ecfe4bbc341767917b7cf6965711"; };
    "tunnel@npm:0.0.6" = { filename = "tunnel-npm-0.0.6-b1c0830ea4-c362948df9.zip"; sha512 = "c362948df9ad34b649b5585e54ce2838fa583aa3037091aaed66793c65b423a264e5229f0d7e9a95513a795ac2bd4cb72cda7e89a74313f182c1e9ae0b0994fa"; };
    "type-check@npm:0.4.0" = { filename = "type-check-npm-0.4.0-60565800ce-ec688ebfc9.zip"; sha512 = "ec688ebfc9c45d0c30412e41ca9c0cdbd704580eb3a9ccf07b9b576094d7b86a012baebc95681999dd38f4f444afd28504cb3a89f2ef16b31d4ab61a0739025a"; };
    "type-fest@npm:0.20.2" = { filename = "type-fest-npm-0.20.2-b36432617f-4fb3272df2.zip"; sha512 = "4fb3272df21ad1c552486f8a2f8e115c09a521ad7a8db3d56d53718d0c907b62c6e9141ba5f584af3f6830d0872c521357e512381f24f7c44acae583ad517d73"; };
    "typed-rest-client@npm:1.8.9" = { filename = "typed-rest-client-npm-1.8.9-97c1fb6d71-615c95872d.zip"; sha512 = "615c95872d9b4d4caa7eb44d639d9044fc41602a16c3855b87deae9e97d6df168c9501a40a1fe003ced4984335684b3dfdadcf24ac0b50657f4cd9026df40e1c"; };
    "typescript@npm:4.9.3" = { filename = "typescript-npm-4.9.3-228c75fdd3-17b8f81605.zip"; sha512 = "17b8f816050b412403e38d48eef0e893deb6be522d6dc7caf105e54a72e34daf6835c447735fd2b28b66784e72bfbf87f627abb4818a8e43d1fa8106396128dc"; };
    "typescript@patch:typescript@npm%3A4.9.3#~builtin<compat/typescript>::version=4.9.3&hash=d73830" = { filename = "typescript-patch-b9b216bc0d-67ca21a387.zip"; sha512 = "67ca21a387c0572f1c04936e638dde7782c5aa520c3754aadc7cc9b7c915da9ebc3e27c601bfff4ccb7d7264e82dce6d277ada82ec09dc75024349e0ef64926d"; };
    "uc.micro@npm:1.0.6" = { filename = "uc.micro-npm-1.0.6-36f3dc2fc4-6898bb5563.zip"; sha512 = "6898bb556319a38e9cf175e3628689347bd26fec15fc6b29fa38e0045af63075ff3fea4cf1fdba9db46c9f0cbf07f2348cd8844889dd31ebd288c29fe0d27e7a"; };
    "underscore@npm:1.13.6" = { filename = "underscore-npm-1.13.6-3ebe9d92fb-d5cedd14a9.zip"; sha512 = "d5cedd14a9d0d91dd38c1ce6169e4455bb931f0aaf354108e47bd46d3f2da7464d49b2171a5cf786d61963204a42d01ea1332a903b7342ad428deaafaf70ec36"; };
    "unique-filename@npm:2.0.1" = { filename = "unique-filename-npm-2.0.1-183c6c7c2b-807acf3381.zip"; sha512 = "807acf3381aff319086b64dc7125a9a37c09c44af7620bd4f7f3247fcd5565660ac12d8b80534dcbfd067e6fe88a67e621386dd796a8af828d1337a8420a255f"; };
    "unique-slug@npm:3.0.0" = { filename = "unique-slug-npm-3.0.0-0b82e51577-49f8d915ba.zip"; sha512 = "49f8d915ba7f0101801b922062ee46b7953256c93ceca74303bd8e6413ae10aa7e8216556b54dc5382895e8221d04f1efaf75f945c2e4a515b4139f77aa6640c"; };
    "unzipper@npm:0.10.11" = { filename = "unzipper-npm-0.10.11-7a1d871174-006cd43ec4.zip"; sha512 = "006cd43ec4d6df47d86aa6b15044a606f50cdcd6a3d6f96f64f54ca0b663c09abb221f76edca0e9592511036d37ea094b1d76ce92c5bf10d7c6eb56f0be678f8"; };
    "uri-js@npm:4.4.1" = { filename = "uri-js-npm-4.4.1-66d11cbcaf-7167432de6.zip"; sha512 = "7167432de6817fe8e9e0c9684f1d2de2bb688c94388f7569f7dbdb1587c9f4ca2a77962f134ec90be0cc4d004c939ff0d05acc9f34a0db39a3c797dada262633"; };
    "url-join@npm:4.0.1" = { filename = "url-join-npm-4.0.1-e1f4415722-f74e868bf2.zip"; sha512 = "f74e868bf25dbc8be6a8d7237d4c36bb5b6c62c72e594d5ab1347fe91d6af7ccd9eb5d621e30152e4da45c2e9a26bec21390e911ab54a62d4d82e76028374ee5"; };
    "util-deprecate@npm:1.0.2" = { filename = "util-deprecate-npm-1.0.2-e3fe1a219c-474acf1146.zip"; sha512 = "474acf1146cb2701fe3b074892217553dfcf9a031280919ba1b8d651a068c9b15d863b7303cb15bd00a862b498e6cf4ad7b4a08fb134edd5a6f7641681cb54a2"; };
    "v8-compile-cache@npm:2.3.0" = { filename = "v8-compile-cache-npm-2.3.0-961375f150-adb0a271ea.zip"; sha512 = "adb0a271eaa2297f2f4c536acbfee872d0dd26ec2d76f66921aa7fc437319132773483344207bdbeee169225f4739016d8d2dbf0553913a52bb34da6d0334f8e"; };
    "vsce@npm:2.14.0" = { filename = "vsce-npm-2.14.0-c875d1964f-1d74c17b0f.zip"; sha512 = "1d74c17b0fc2e1c0e5b0f6746db48c4b7111c3bde1c6e85e23511766ee428c4763b1d0ec74af7d1acfa9041dabc798b208546f95f79dd1d8eb00903a23f7a7c7"; };
    "vscode-jsonrpc@npm:6.0.0" = { filename = "vscode-jsonrpc-npm-6.0.0-4e625ea1b8-3a67a56f28.zip"; sha512 = "3a67a56f287e8c449f2d9752eedf91e704dc7b9a326f47fb56ac07667631deb45ca52192e9bccb2ab108764e48409d70fa64b930d46fc3822f75270b111c5f53"; };
    "vscode-languageclient@npm:7.0.0" = { filename = "vscode-languageclient-npm-7.0.0-c177c3e495-fde7122e96.zip"; sha512 = "fde7122e96838f0de1940dba80fc4b6bb80717695dbfaff005b9d44eeea371b7f09daedefaebcbf0ff278f67446e37837ec0730ddbc7dbd82aca5d8567065594"; };
    "vscode-languageserver-protocol@npm:3.16.0" = { filename = "vscode-languageserver-protocol-npm-3.16.0-7e2ca72c58-ac30cbe4b7.zip"; sha512 = "ac30cbe4b778344f7b93defbaa1332dcb5a5a3a0afda6b88618a9ed44093c1ae1d2f11548bdcff42a73bb46943df025d4fe721559144dd7bf25ae60663aabe06"; };
    "vscode-languageserver-types@npm:3.16.0" = { filename = "vscode-languageserver-types-npm-3.16.0-bd03fd2d40-7a44fb10b9.zip"; sha512 = "7a44fb10b9fbeb9529f832337b7f0430fc6275d62945b86851d425a950e22da3917ef5f6c552688191769dd1eae047c6ee9ec3d9f2280498353007c2dfe0725c"; };
    "which@npm:2.0.2" = { filename = "which-npm-2.0.2-320ddf72f7-1a5c563d3c.zip"; sha512 = "1a5c563d3c1b52d5f893c8b61afe11abc3bab4afac492e8da5bde69d550de701cf9806235f20a47b5c8fa8a1d6a9135841de2596535e998027a54589000e66d1"; };
    "wide-align@npm:1.1.3" = { filename = "wide-align-npm-1.1.3-48c7d4953c-d09c801265.zip"; sha512 = "d09c8012652a9e6cab3e82338d1874a4d7db2ad1bd19ab43eb744acf0b9b5632ec406bdbbbb970a8f4771a7d5ef49824d038ba70aa884e7723f5b090ab87134d"; };
    "wide-align@npm:1.1.5" = { filename = "wide-align-npm-1.1.5-889d77e592-d5fc37cd56.zip"; sha512 = "d5fc37cd561f9daee3c80e03b92ed3e84d80dde3365a8767263d03dacfc8fa06b065ffe1df00d8c2a09f731482fcacae745abfbb478d4af36d0a891fad4834d3"; };
    "word-wrap@npm:1.2.3" = { filename = "word-wrap-npm-1.2.3-7fb15ab002-30b48f91fc.zip"; sha512 = "30b48f91fcf12106ed3186ae4fa86a6a1842416df425be7b60485de14bec665a54a68e4b5156647dec3a70f25e84d270ca8bc8cd23182ed095f5c7206a938c1f"; };
    "workerpool@npm:6.1.0" = { filename = "workerpool-npm-6.1.0-e1ce970c3c-519d03a4d0.zip"; sha512 = "519d03a4d008fd95ff9e1a583afe537e6a0eecd8250452044e390db3e1dc4ce91616a8ee6c4bba9a2fda38440c2666664c31b50b5a9fd05cc43c739df54d5781"; };
    "wrap-ansi@npm:7.0.0" = { filename = "wrap-ansi-npm-7.0.0-ad6e1a0554-a790b846fd.zip"; sha512 = "a790b846fd4505de962ba728a21aaeda189b8ee1c7568ca5e817d85930e06ef8d1689d49dbf0e881e8ef84436af3a88bc49115c2e2788d841ff1b8b5b51a608b"; };
    "wrappy@npm:1.0.2" = { filename = "wrappy-npm-1.0.2-916de4d4b3-159da4805f.zip"; sha512 = "159da4805f7e84a3d003d8841557196034155008f817172d4e986bd591f74aa82aa7db55929a54222309e01079a65a92a9e6414da5a6aa4b01ee44a511ac3ee5"; };
    "xml2js@npm:0.4.23" = { filename = "xml2js-npm-0.4.23-93a8b2e10b-ca0cf2dfbf.zip"; sha512 = "ca0cf2dfbf6deeaae878a891c8fbc0db6fd04398087084edf143cdc83d0509ad0fe199b890f62f39c4415cf60268a27a6aed0d343f0658f8779bd7add690fa98"; };
    "xmlbuilder@npm:11.0.1" = { filename = "xmlbuilder-npm-11.0.1-b8b04dc929-7152695e16.zip"; sha512 = "7152695e16f1a9976658215abab27e55d08b1b97bca901d58b048d2b6e106b5af31efccbdecf9b07af37c8377d8e7e821b494af10b3a68b0ff4ae60331b415b0"; };
    "y18n@npm:5.0.8" = { filename = "y18n-npm-5.0.8-5f3a0a7e62-54f0fb9562.zip"; sha512 = "54f0fb95621ee60898a38c572c515659e51cc9d9f787fb109cef6fde4befbe1c4602dc999d30110feee37456ad0f1660fa2edcfde6a9a740f86a290999550d30"; };
    "yallist@npm:4.0.0" = { filename = "yallist-npm-4.0.0-b493d9e907-343617202a.zip"; sha512 = "343617202af32df2a15a3be36a5a8c0c8545208f3d3dfbc6bb7c3e3b7e8c6f8e7485432e4f3b88da3031a6e20afa7c711eded32ddfb122896ac5d914e75848d5"; };
    "yargs-parser@npm:20.2.4" = { filename = "yargs-parser-npm-20.2.4-1de20916a6-d251998a37.zip"; sha512 = "d251998a374b2743a20271c2fd752b9fbef24eb881d53a3b99a7caa5e8227fcafd9abf1f345ac5de46435821be25ec12189a11030c12ee6481fef6863ed8b924"; };
    "yargs-parser@npm:20.2.9" = { filename = "yargs-parser-npm-20.2.9-a1d19e598d-8bb69015f2.zip"; sha512 = "8bb69015f2b0ff9e17b2c8e6bfe224ab463dd00ca211eece72a4cd8a906224d2703fb8a326d36fdd0e68701e201b2a60ed7cf81ce0fd9b3799f9fe7745977ae3"; };
    "yargs-unparser@npm:2.0.0" = { filename = "yargs-unparser-npm-2.0.0-930f3ff3f6-68f9a542c6.zip"; sha512 = "68f9a542c6927c3768c2f16c28f71b19008710abd6b8f8efbac6dcce26bbb68ab6503bed1d5994bdbc2df9a5c87c161110c1dfe04c6a3fe5c6ad1b0e15d9a8a3"; };
    "yargs@npm:16.2.0" = { filename = "yargs-npm-16.2.0-547873d425-b14afbb51e.zip"; sha512 = "b14afbb51e3251a204d81937c86a7e9d4bdbf9a2bcee38226c900d00f522969ab675703bee2a6f99f8e20103f608382936034e64d921b74df82b63c07c5e8f59"; };
    "yauzl@npm:2.10.0" = { filename = "yauzl-npm-2.10.0-72e70ea021-7f21fe0bba.zip"; sha512 = "7f21fe0bbad6e2cb130044a5d1d0d5a0e5bf3d8d4f8c4e6ee12163ce798fee3de7388d22a7a0907f563ac5f9d40f8699a223d3d5c1718da90b0156da6904022b"; };
    "yazl@npm:2.5.1" = { filename = "yazl-npm-2.5.1-07fc697bef-daec5154b5.zip"; sha512 = "daec5154b5485d8621bfea359e905ddca0b2f068430a4aa0a802bf5d67391157a383e0c2767acccbf5964264851da643bc740155a9458e2d8dce55b94c1cc2ed"; };
    "yocto-queue@npm:0.1.0" = { filename = "yocto-queue-npm-0.1.0-c6c9a7db29-f77b3d8d00.zip"; sha512 = "f77b3d8d00310def622123df93d4ee654fc6a0096182af8bd60679ddcdfb3474c56c6c7190817c84a2785648cdee9d721c0154eb45698c62176c322fb46fc700"; };
  };

in
optionalOverride overrideAttrs project
