//! Computation of type equality for contracts.
//!
//! Determine if two contracts are equal as opaque types. Used to decide if two contract should
//! unify.
//!
//! ## Aliases
//!
//! One basic case we want to handle is aliases, which come in handy for parametrized contracts.
//! For example, in the following:
//!
//! `let Alias = Foo "bar" "baz" in ...`.
//!
//! We want to equate `Alias` with `Foo "bar" "baz"`.
//!
//! We also want to equate different aliases with the same definition:
//! `let Alias' = Foo "bar" "baz" in ...`, or `let Alias' = Alias in ...`.
//!
//! We want that `Alias type_eq Alias'`.
//!
//! ## Recursion
//!
//! We must refrain from following all variables links blindly, as there could be cycles in the
//! graph leading to an infinite loop:
//!
//! ```nickel
//! {
//!   Foo = Bar,
//!   Bar = Foo,
//! }
//! ```
//!
//! Because we just follows variables, and don't apply functions, we can detect cycles while
//! walking the graph. Still, as it is potentially performed many times during typechecking, type
//! equality ought to stay reasonably cheap. We choose to just set an arbitrary limit (the gas) on
//! the number of variable links that the type equality may follow. Doing so, we don't have to
//! worry about loops anymore.
//!
//! Note: we currently don't support recursive let or recursive record definitions, so this example
//! wouldn't work anyway, and there's no way to have an infinite cycle. Style, gas is a simple way
//! to bound the work done by the type equality computation.
//!
//! ## Equality on terms
//!
//! The terms inside a type may be arbitrarily complex. Primops applications, `match`, and the like
//! are quite unlikely to appear inside an annotation (they surely appear inside contract
//! definitions, both are usually put in a variable first - they unlinkely to appear _inline_ in a
//! type or contract annotation is what we mean)
//!
//! We don't want to compare functions syntactically either. The spirit of this implementation is
//! to structurally equate aliases and simple constructs that are likely to appear inlined inside
//! an annotation (applications, records, primitive constants and arrays, mostly).
//!
//! We first test for physical equality (both as an optimization and to detect two variables
//! pointing to the same contract definition in the AST). If the comparison fails, we perform
//! structural recursion, unfolding simple forms and following variables with a limited number of
//! times. For anything more complex, we bail out (returning `false`).

use super::*;
use crate::{
    bytecode::ast::{primop::PrimOp, record},
    identifier::LocIdent,
    term::IndexMap,
    typ::VarKind,
};

/// The maximal number of variable links we want to unfold before abandoning the check. It should
/// stay low, but has been fixed arbitrarily: feel fee to increase reasonably if it turns out
/// legitimate type equalities between simple contracts are unduly rejected in practice.
pub const MAX_GAS: u8 = 12;

/// State threaded through the type equality computation.
#[derive(Copy, Clone, Default)]
struct State {
    /// Used to generate temporary rigid type variables for substituting type variables when
    /// comparing foralls. Those ids never escape the type equality computations and are used
    /// solely as rigid type variables: this is why they don't need proper allocation in the
    /// unification table or to care about those ids clashing with the one generated by the
    /// typechecker. Generated type constants simply needs to be unique for the duration of the
    /// type equality computation.
    var_uid: usize,

    /// The current gas remaining for variable substitutions. Once it reaches zero and we encounter
    /// a variable, we abort the computation and return false.
    gas: u8,
}

impl State {
    fn new() -> Self {
        State {
            var_uid: 0,
            gas: MAX_GAS,
        }
    }

    /// Create a fresh unique id for a rigid type variable.
    fn fresh_cst_id(&mut self) -> VarId {
        let result = self.var_uid;
        self.var_uid += 1;
        result
    }

    /// Try to consume one unit of gas for a variable substitution. Return true in case of success,
    /// or false if the gas was already at zero.
    fn use_gas(&mut self) -> bool {
        if self.gas == 0 {
            false
        } else {
            self.gas -= 1;
            true
        }
    }
}

/// Values that can be statically compared as Nickel types.
pub trait TypeEq<'ast> {
    /// Compute type equality.
    ///
    /// # Parameters
    ///
    /// - `env`: an environment mapping variables to their definition
    fn type_eq(&self, other: &Self, env1: &TermEnv<'ast>, env2: &TermEnv<'ast>) -> bool {
        self.type_eq_bounded(other, &mut State::new(), env1, env2)
    }

    /// Compute type equality with a bounded number of variable links, stored in `state`.
    fn type_eq_bounded(
        &self,
        other: &Self,
        state: &mut State,
        env1: &TermEnv<'ast>,
        env2: &TermEnv<'ast>,
    ) -> bool;
}

impl<'ast, T> TypeEq<'ast> for &'ast [T]
where
    T: TypeEq<'ast>,
{
    fn type_eq_bounded(
        &self,
        other: &Self,
        state: &mut State,
        env1: &TermEnv<'ast>,
        env2: &TermEnv<'ast>,
    ) -> bool {
        self.len() == other.len()
            && self
                .iter()
                .zip(other.iter())
                .all(|(x1, x2)| x1.type_eq_bounded(x2, state, env1, env2))
    }
}

impl<'ast, T> TypeEq<'ast> for Option<T>
where
    T: TypeEq<'ast>,
{
    fn type_eq_bounded(
        &self,
        other: &Self,
        state: &mut State,
        env1: &TermEnv<'ast>,
        env2: &TermEnv<'ast>,
    ) -> bool {
        match (self, other) {
            (Some(x1), Some(x2)) => x1.type_eq_bounded(x2, state, env1, env2),
            (None, None) => true,
            _ => false,
        }
    }
}

impl<'ast> TypeEq<'ast> for Ast<'ast> {
    fn type_eq_bounded(
        &self,
        other: &Self,
        state: &mut State,
        env1: &TermEnv<'ast>,
        env2: &TermEnv<'ast>,
    ) -> bool {
        // Test for physical equality as both an optimization and a way to cheaply equate complex
        // contracts that happen to point to the same definition (while the purposely limited
        // structural checks below may reject the equality)
        if std::ptr::eq(self, other) && Environment::ptr_eq(&env1.0, &env2.0) {
            return true;
        }

        match (&self.node, &other.node) {
            (Node::Null, Node::Null) => true,
            (Node::Bool(b1), Node::Bool(b2)) => b1 == b2,
            (Node::Number(n1), Node::Number(n2)) => n1 == n2,
            (Node::String(s1), Node::String(s2)) => s1 == s2,
            (
                Node::EnumVariant {
                    tag: tag1,
                    arg: arg1,
                },
                Node::EnumVariant {
                    tag: tag2,
                    arg: arg2,
                },
            ) => {
                let arg_eq = match (arg1.as_ref(), arg2.as_ref()) {
                    (Some(arg1), Some(arg2)) => arg1.type_eq_bounded(arg2, state, env1, env2),
                    (None, None) => true,
                    _ => false,
                };

                tag1 == tag2 && arg_eq
            }
            // We only compare string chunks when they represent a plain string (they don't contain any
            // interpolated expression), as static string may be currently parsed as such. We return
            // false for anything more complex.
            (Node::StringChunks(scs1), Node::StringChunks(scs2)) => {
                scs1.len() == scs2.len()
                    && scs1
                        .iter()
                        .zip(scs2.iter())
                        .all(|(chunk1, chunk2)| match (chunk1, chunk2) {
                            (StringChunk::Literal(s1), StringChunk::Literal(s2)) => s1 == s2,
                            _ => false,
                        })
            }
            (
                Node::App {
                    head: head1,
                    args: args1,
                },
                Node::App {
                    head: head2,
                    args: args2,
                },
            ) => {
                head1.type_eq_bounded(head2, state, env1, env2)
                    && args1.type_eq_bounded(args2, state, env1, env2)
            }
            // All variables must be bound at this stage. This is checked by the typechecker when
            // walking annotations. However, we may assume that `env` is a local environment (e.g. that
            // it doesn't include the stdlib). In that case, free variables (unbound) may be deemed
            // equal if they have the same identifier: whatever global environment the term will be put
            // in, free variables are not redefined locally and will be bound to the same value in any
            // case.
            (Node::Var(id1), Node::Var(id2))
                if env1.0.get(&id1.ident()).is_none() && env2.0.get(&id2.ident()).is_none() =>
            {
                id1 == id2
            }
            // If both variables are equal and their environment are physically equal, then they point
            // to the same thing.
            //
            // This case is supposed to handle co-recursive contracts such as `{Foo = Bar, Bar = Foo}`.
            // Although we don't build recursive environment yet, we might in the future.
            (Node::Var(id1), Node::Var(id2))
                if id1 == id2 && Environment::ptr_eq(&env1.0, &env2.0) =>
            {
                true
            }
            (Node::Var(id), _) => {
                state.use_gas()
                    && env1
                        .0
                        .get(&id.ident())
                        .map(|(ast1, env1)| ast1.type_eq_bounded(other, state, env1, env2))
                        .unwrap_or(false)
            }
            (_, Node::Var(id)) => {
                state.use_gas()
                    && env2
                        .0
                        .get(&id.ident())
                        .map(|(ast2, env2)| self.type_eq_bounded(ast2, state, env1, env2))
                        .unwrap_or(false)
            }
            (Node::Record(r1), Node::Record(r2)) => todo!() && r1.open == r2.open,
            (Node::Array(elts1), Node::Array(elts2)) => {
                elts1.type_eq_bounded(elts2, state, env1, env2)
            }
            // We must compare the inner values as well as the corresponding contracts or type
            // annotations.
            (
                Node::Annotated {
                    annot: annot1,
                    inner: inner1,
                },
                Node::Annotated {
                    annot: annot2,
                    inner: inner2,
                },
            ) => {
                // Questions:
                // - does it really make sense to compare the annotations?
                // - does it even happen to have contracts having themselves type annotations?
                // - and in the latter case, should they be declared unequal because of that?
                //
                // The answer to the last question is probably yes, because contracts are fundamentally
                // as powerful as function application, so they can change their argument.

                annot1.type_eq_bounded(annot2, state, env1, env2)
                    && inner1.type_eq_bounded(inner2, state, env1, env2)
            }
            (
                Node::PrimOpApp {
                    op: PrimOp::RecordStatAccess(id1),
                    args: args1,
                },
                Node::PrimOpApp {
                    op: PrimOp::RecordStatAccess(id2),
                    args: args2,
                },
            ) => id1 == id2 && args1.type_eq_bounded(args2, state, env1, env2),
            (Node::Type(ty1), Node::Type(ty2)) => ty1.type_eq_bounded(ty2, state, env1, env2),
            // We don't treat imports, parse errors, nor pairs of terms that don't have the same shape
            _ => false,
        }
    }
}

impl<'ast> TypeEq<'ast> for Type<'ast> {
    /// Perform the type equality comparison on types. Structurally recurse into type constructors and
    /// test that subtypes or subterms (contracts) are equals.
    ///
    /// This function piggy backs on the type equality for [super::UnifType] implementation,
    /// because we need to instantiate `foralls` with rigid type variables to properly compare
    /// them.
    ///
    fn type_eq_bounded(
        &self,
        other: &Self,
        state: &mut State,
        env1: &TermEnv<'ast>,
        env2: &TermEnv<'ast>,
    ) -> bool {
        let self_as_utype = UnifType::from_type(self.clone(), env1);
        let other_as_utype = UnifType::from_type(other.clone(), env2);
        utype_eq_bounded(state, &self_as_utype, env1, &other_as_utype, env2)
    }
}

impl<'ast, T> TypeEq<'ast> for IndexMap<LocIdent, T>
where
    T: TypeEq<'ast>,
{
    fn type_eq_bounded(
        &self,
        other: &Self,
        state: &mut State,
        env1: &TermEnv<'ast>,
        env2: &TermEnv<'ast>,
    ) -> bool {
        map1.len() == map2.len()
            && map1.iter().all(|(id, v1)| {
                map2.get(id)
                    .map(|v2| f(state, v1, env1, v2, env2))
                    .unwrap_or(false)
            })
    }
}
/// Compute the equality between two hashmaps holding either types or terms.
fn map_eq<'ast, V, F>(
    mut f: F,
    state: &mut State,
    map1: &IndexMap<LocIdent, V>,
    env1: &TermEnv<'ast>,
    map2: &IndexMap<LocIdent, V>,
    env2: &TermEnv<'ast>,
) -> bool
where
    F: FnMut(&mut State, &V, &TermEnv<'ast>, &V, &TermEnv<'ast>) -> bool,
{
    map1.len() == map2.len()
        && map1.iter().all(|(id, v1)| {
            map2.get(id)
                .map(|v2| f(state, v1, env1, v2, env2))
                .unwrap_or(false)
        })
}

/// Convert record rows to a hashmap.
///
/// Require the rows to be closed (i.e. the last element must be `RowEmpty`), otherwise `None` is
/// returned. `None` is returned as well if a type encountered is not row, or if it is a enum row.
fn rrows_as_map<'ast, 'a>(
    erows: &'a UnifRecordRows<'ast>,
) -> Option<IndexMap<LocIdent, &'a UnifType<'ast>>> {
    let map: Option<IndexMap<LocIdent, _>> = erows
        .iter()
        .map(|item| match item {
            RecordRowsElt::Row(RecordRowF { id, typ: types }) => Some((id, types)),
            _ => None,
        })
        .collect();

    map
}

/// Convert enum rows to a hashmap.
///
/// Require the rows to be closed (i.e. the last element must be `RowEmpty`), otherwise `None` is
/// returned. `None` is returned as well if a type encountered is not row type, or if it is a
/// record row.
fn erows_as_map<'ast, 'a>(
    erows: &'a UnifEnumRows<'ast>,
) -> Option<IndexMap<LocIdent, Option<&'a UnifType<'ast>>>> {
    let set: Option<IndexMap<LocIdent, Option<_>>> = erows
        .iter()
        .map(|item| match item {
            EnumRowsElt::Row(EnumRowF { id, typ: types }) => Some((id, types)),
            _ => None,
        })
        .collect();

    set
}

impl<'ast> TypeEq<'ast> for Annotation<'ast> {
    fn type_eq_bounded(
        &self,
        other: &Self,
        state: &mut State,
        env1: &TermEnv<'ast>,
        env2: &TermEnv<'ast>,
    ) -> bool {
        self.typ.type_eq_bounded(&other.typ, state, env1, env2)
            && self
                .contracts
                .type_eq_bounded(&other.contracts, state, env1, env2)
    }
}

impl<'ast> TypeEq<'ast> for record::FieldMetadata<'ast> {
    fn type_eq_bounded(
        &self,
        other: &Self,
        state: &mut State,
        env1: &TermEnv<'ast>,
        env2: &TermEnv<'ast>,
    ) -> bool {
        self.annotation
            .type_eq_bounded(&other.annotation, state, env1, env2)
            && self.opt == other.opt
            && self.not_exported == other.not_exported
            && self.priority == other.priority
    }
}

impl<'ast> TypeEq<'ast> for record::FieldPathElem<'ast> {
    fn type_eq_bounded(
        &self,
        other: &Self,
        _state: &mut State,
        _env1: &TermEnv<'ast>,
        _env2: &TermEnv<'ast>,
    ) -> bool {
        // For now, we don't even try to compare interpolated expressions at all, and only compare
        // static field definitions.
        match (self.try_as_ident(), other.try_as_ident()) {
            (Some(id1), Some(id2)) => id1 == id2,
            _ => false,
        }
    }
}

impl<'ast> TypeEq<'ast> for FieldDef<'ast> {
    /// Check for contract equality between record fields. Fields are equal if they are both without a
    /// definition, or are both defined and their values are equal.
    ///
    /// The attached metadata must be equal as well: most record contracts are written as field with
    /// metadata but without definition. For example, take `{ foo | {bar | Number}}` and `{foo | {bar |
    /// String}}`. Those two record contracts are obviously not equal, but to know that, we have to
    /// look at the contracts of each bar field.
    fn type_eq_bounded(
        &self,
        other: &Self,
        state: &mut State,
        env1: &TermEnv<'ast>,
        env2: &TermEnv<'ast>,
    ) -> bool {
        self.metadata
            .type_eq_bounded(&other.metadata, state, env1, env2)
            && self.path.type_eq_bounded(&other.path, state, env1, env2)
            && self.value.type_eq_bounded(&other.value, state, env1, env2)
    }
}

/// This function isn't implemented through [TypeEq], because it is private. It's used internally
/// by the implementation of [TypeEq] for [crate::bytecode::ast::typ::Type], but it makes a number
/// of assumptions and isn't supposed to be called from the outside. And indeed, computing type
/// equality recursively on unifiable type doesn't make a lot of sense: we can unify them instead.
///
/// For example, we expect to never meet unification variables, and that all the rigid type
/// variables encountered have been introduced by `type_eq_bounded` itself. This is why we don't
/// need unique identifiers that are distinct from the one used during typechecking, and we can
/// just start from `0` when creating a new [State].
fn utype_eq_bounded<'ast>(
    state: &mut State,
    ty1: &UnifType<'ast>,
    env1: &TermEnv<'ast>,
    ty2: &UnifType<'ast>,
    env2: &TermEnv<'ast>,
) -> bool {
    match (ty1, ty2) {
        (UnifType::Concrete { typ: s1, .. }, UnifType::Concrete { typ: s2, .. }) => {
            match (s1, s2) {
                (TypeF::Wildcard(id1), TypeF::Wildcard(id2)) => id1 == id2,
                (TypeF::Dyn, TypeF::Dyn)
                | (TypeF::Number, TypeF::Number)
                | (TypeF::Bool, TypeF::Bool)
                | (TypeF::Symbol, TypeF::Symbol)
                | (TypeF::String, TypeF::String) => true,
                (
                    TypeF::Dict {
                        type_fields: uty1,
                        flavour: attrs1,
                    },
                    TypeF::Dict {
                        type_fields: uty2,
                        flavour: attrs2,
                    },
                ) if attrs1 == attrs2 => utype_eq_bounded(state, uty1, env1, uty2, env2),
                (TypeF::Array(uty1), TypeF::Array(uty2)) => {
                    utype_eq_bounded(state, uty1, env1, uty2, env2)
                }
                (TypeF::Arrow(s1, t1), TypeF::Arrow(s2, t2)) => {
                    utype_eq_bounded(state, s1, env1, s2, env2)
                        && utype_eq_bounded(state, t1, env1, t2, env2)
                }
                (TypeF::Enum(uty1), TypeF::Enum(uty2)) => {
                    fn utype_eq_bounded_wrapper<'ast>(
                        state: &mut State,
                        uty1: &Option<&UnifType<'ast>>,
                        env1: &TermEnv<'ast>,
                        uty2: &Option<&UnifType<'ast>>,
                        env2: &TermEnv<'ast>,
                    ) -> bool {
                        match (uty1, uty2) {
                            (Some(uty1), Some(uty2)) => {
                                utype_eq_bounded(state, *uty1, env1, *uty2, env2)
                            }
                            (None, None) => true,
                            _ => false,
                        }
                    }

                    let map1 = erows_as_map(uty1);
                    let map2 = erows_as_map(uty2);

                    map1.zip(map2)
                        .map(|(m1, m2)| {
                            map_eq(utype_eq_bounded_wrapper, state, &m1, env1, &m2, env2)
                        })
                        .unwrap_or(false)
                }
                (TypeF::Record(uty1), TypeF::Record(uty2)) => {
                    fn utype_eq_bounded_wrapper<'ast>(
                        state: &mut State,
                        uty1: &&UnifType<'ast>,
                        env1: &TermEnv<'ast>,
                        uty2: &&UnifType<'ast>,
                        env2: &TermEnv<'ast>,
                    ) -> bool {
                        utype_eq_bounded(state, *uty1, env1, *uty2, env2)
                    }

                    let map1 = rrows_as_map(uty1);
                    let map2 = rrows_as_map(uty2);

                    map1.zip(map2)
                        .map(|(m1, m2)| {
                            map_eq(utype_eq_bounded_wrapper, state, &m1, env1, &m2, env2)
                        })
                        .unwrap_or(false)
                }
                (TypeF::Contract((t1, env1)), TypeF::Contract((t2, env2))) => {
                    t1.type_eq_bounded(t2, state, env1, env2)
                }
                (
                    TypeF::Forall {
                        var: var1,
                        var_kind: var_kind1,
                        body: body1,
                    },
                    TypeF::Forall {
                        var: var2,
                        var_kind: var_kind2,
                        body: body2,
                    },
                ) => {
                    let cst_id = state.fresh_cst_id();

                    if var_kind1 != var_kind2 {
                        return false;
                    }

                    let body1 = body1.clone();
                    let body2 = body2.clone();

                    let (uty1_subst, uty2_subst) = match var_kind1 {
                        VarKind::Type => (
                            body1.subst(var1, &UnifType::Constant(cst_id)),
                            body2.subst(var2, &UnifType::Constant(cst_id)),
                        ),
                        VarKind::RecordRows { .. } => (
                            body1.subst(var1, &UnifRecordRows::Constant(cst_id)),
                            body2.subst(var2, &UnifRecordRows::Constant(cst_id)),
                        ),
                        VarKind::EnumRows { .. } => (
                            body1.subst(var1, &UnifEnumRows::Constant(cst_id)),
                            body2.subst(var2, &UnifEnumRows::Constant(cst_id)),
                        ),
                    };

                    utype_eq_bounded(state, &uty1_subst, env1, &uty2_subst, env2)
                }
                // We can't compare type variables without knowing what they are instantiated to,
                // and all type variables should have been substituted at this point, so we bail
                // out.
                _ => false,
            }
        }
        (UnifType::UnifVar { id: id1, .. }, UnifType::UnifVar { id: id2, .. }) => {
            debug_assert!(
                false,
                "we shouldn't come across unification variables during type equality computation"
            );
            id1 == id2
        }
        (UnifType::Constant(i1), UnifType::Constant(i2)) => i1 == i2,
        _ => false,
    }
}
