use criterion::{criterion_group, criterion_main, Criterion};
use nickel_lang_utilities::{bench_terms, Bench, EvalMode};
use pprof::criterion::{Output, PProfProfiler};

pub fn benches() {
    let config =
        Criterion::default().with_profiler(PProfProfiler::new(100, Output::Flamegraph(None)));
    let mut criterion: Criterion<_> = config.configure_from_args();
    let target = bench_terms(vec![
        Bench::bench(
            "foldr strings 50",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/fold",
            Some("right.strings"),
            50,
            EvalMode::Normal,
        ),
        Bench::bench(
            "foldr deepseq strings 30",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/fold",
            Some("right.strings"),
            30,
            EvalMode::DeepSeq,
        ),
        Bench::bench(
            "foldr nums 50",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/fold",
            Some("right.nums"),
            50,
            EvalMode::Normal,
        ),
        Bench::bench(
            "foldr deepseq nums 30",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/fold",
            Some("right.nums"),
            30,
            EvalMode::DeepSeq,
        ),
        Bench::bench(
            "foldr arrays 50",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/fold",
            Some("right.arrays"),
            50,
            EvalMode::Normal,
        ),
        Bench::bench(
            "foldr deepseq arrays 30",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/fold",
            Some("right.arrays"),
            30,
            EvalMode::DeepSeq,
        ),
        Bench::bench(
            "foldl strings 50",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/fold",
            Some("left.strings"),
            50,
            EvalMode::Normal,
        ),
        Bench::bench(
            "foldl deepseq strings 30",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/fold",
            Some("left.strings"),
            30,
            EvalMode::DeepSeq,
        ),
        Bench::bench(
            "foldl nums 50",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/fold",
            Some("left.nums"),
            50,
            EvalMode::Normal,
        ),
        Bench::bench(
            "foldl deepseq nums 30",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/fold",
            Some("left.nums"),
            30,
            EvalMode::DeepSeq,
        ),
        Bench::bench(
            "foldl arrays 50",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/fold",
            Some("left.arrays"),
            50,
            EvalMode::Normal,
        ),
        Bench::bench(
            "foldl deepseq arrays 30",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/fold",
            Some("left.arrays"),
            30,
            EvalMode::DeepSeq,
        ),
        Bench::bench(
            "generate normal 50",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/generate",
            None,
            50,
            EvalMode::Normal,
        ),
        Bench::bench(
            "generate deepseq 30",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/generate",
            None,
            30,
            EvalMode::DeepSeq,
        ),
        Bench::bench(
            "map normal 50",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/map",
            None,
            50,
            EvalMode::Normal,
        ),
        Bench::bench(
            "map deepseq 30",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/map",
            None,
            30,
            EvalMode::DeepSeq,
        ),
        Bench::bench(
            "pipe normal 20",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/pipe",
            None,
            20,
            EvalMode::Normal,
        ),
        Bench::bench(
            "pipe deepseq 20",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/pipe",
            None,
            20,
            EvalMode::DeepSeq,
        ),
        Bench::bench(
            "sort normal",
            env!("CARGO_MANIFEST_DIR"),
            "arrays/sort",
            None,
            20,
            EvalMode::Normal,
        ),
    ]);
    target(&mut criterion);
}
criterion_main!(benches);
