# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  makam = nodeEnv.buildNodePackage {
    name = "makam";
    packageName = "makam";
    version = "0.7.17";
    src = fetchurl {
      url = "https://registry.npmjs.org/makam/-/makam-0.7.17.tgz";
      sha512 = "d4TZl74LMpFoouO0Yba/fDJKEdVW7FGTBMNCNti0mxI7u/yj4oVBueQf890F8v+oKcS/jfLvl0CBf/pbqOdoXA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "The Makam metalanguage -- a tool for rapid language prototyping";
      homepage = http://astampoulis.github.io/makam/;
      license = "GPL-3.0";
    };
    production = true;
    bypassCache = true;
  };
}