# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  makam = nodeEnv.buildNodePackage {
    name = "makam";
    packageName = "makam";
    version = "0.7.20";
    src = fetchurl {
      url = "https://registry.npmjs.org/makam/-/makam-0.7.20.tgz";
      sha512 = "93bvr4v+KBpa3NY49m3hKUw1Qdf3wFQR3z80ZiqGvEAKPtgnxIcosLde2kYFM6hQ9g18lxKAAgOpGkCXPCRR5A==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "The Makam metalanguage -- a tool for rapid language prototyping";
      homepage = http://astampoulis.github.io/makam/;
      license = "GPL-3.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}