### /main.ncl
(let { x } = { x = 1 } in x) : _
### [[request]]
### type = "Hover"
### textDocument.uri = "file:///main.ncl"
### position = { line = 0, character = 7 }
###
### [[request]]
### type = "Hover"
### textDocument.uri = "file:///main.ncl"
### position = { line = 0, character = 15 }
###
### [[request]]
### type = "Hover"
### textDocument.uri = "file:///main.ncl"
### position = { line = 0, character = 26 }
